/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './event-create';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../providers/event-data';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import19 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import20 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/datetime/datetime.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import24 from 'ionic-angular/config/config';
import * as import25 from '@angular/core/src/linker/element_ref';
import * as import26 from 'ionic-angular/navigation/view-controller';
import * as import27 from 'ionic-angular/components/app/app';
import * as import28 from 'ionic-angular/components/toolbar/toolbar';
import * as import29 from 'ionic-angular/util/keyboard';
import * as import30 from '@angular/core/src/zone/ng_zone';
import * as import31 from 'ionic-angular/components/tabs/tabs';
import * as import32 from 'ionic-angular/util/form';
import * as import33 from 'ionic-angular/components/item/item-reorder';
import * as import34 from 'ionic-angular/platform/platform';
import * as import35 from 'ionic-angular/components/picker/picker';
import * as import36 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import37 from 'ionic-angular/components/navbar/navbar';
import * as import38 from 'ionic-angular/components/label/label';
import * as import39 from '@angular/forms/src/directives/ng_model';
import * as import40 from '@angular/forms/src/directives/ng_control';
import * as import41 from '@angular/forms/src/directives/ng_control_status';
import * as import42 from 'ionic-angular/components/input/input';
import * as import43 from 'ionic-angular/components/item/item';
import * as import44 from 'ionic-angular/components/datetime/datetime';
import * as import45 from '@angular/forms/src/directives/control_value_accessor';
import * as import46 from 'ionic-angular/components/button/button';
import * as import47 from 'ionic-angular/components/content/content';
export class Wrapper_EventCreatePage {
  context:import0.EventCreatePage;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.EventCreatePage(p0,p1);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_EventCreatePage_Host:import2.RenderComponentType = (null as any);
class _View_EventCreatePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _EventCreatePage_0_4:Wrapper_EventCreatePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_EventCreatePage_Host0,renderType_EventCreatePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-event-create',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_EventCreatePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._EventCreatePage_0_4 = new Wrapper_EventCreatePage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.EventData));
    this._appEl_0.initComponent(this._EventCreatePage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._EventCreatePage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.EventCreatePage) && (0 === requestNodeIndex))) { return this._EventCreatePage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._EventCreatePage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_EventCreatePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_EventCreatePage_Host === (null as any))) { (renderType_EventCreatePage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_EventCreatePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const EventCreatePageNgFactory:import11.ComponentFactory<import0.EventCreatePage> = new import11.ComponentFactory<import0.EventCreatePage>('page-event-create',viewFactory_EventCreatePage_Host0,import0.EventCreatePage);
const styles_EventCreatePage:any[] = ([] as any[]);
var renderType_EventCreatePage:import2.RenderComponentType = (null as any);
class _View_EventCreatePage0 extends import1.AppView<import0.EventCreatePage> {
  _el_0:any;
  _Header_0_3:import12.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import13.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import14.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Content_9_4:import15.Wrapper_Content;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import3.AppElement;
  _Item_11_4:import16.Wrapper_Item;
  _ItemContent_11_5:import16.Wrapper_ItemContent;
  _query_Label_11_0:import17.QueryList<any>;
  _query_Button_11_1:import17.QueryList<any>;
  _query_Icon_11_2:import17.QueryList<any>;
  _text_12:any;
  _el_13:any;
  _Label_13_3:import18.Wrapper_Label;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import3.AppElement;
  _NgModel_16_4:import19.Wrapper_NgModel;
  _NgControl_16_5:any;
  _NgControlStatus_16_6:import20.Wrapper_NgControlStatus;
  _TextInput_16_7:import21.Wrapper_TextInput;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  /*private*/ _appEl_19:import3.AppElement;
  _Item_19_4:import16.Wrapper_Item;
  _ItemContent_19_5:import16.Wrapper_ItemContent;
  _query_Label_19_0:import17.QueryList<any>;
  _query_Button_19_1:import17.QueryList<any>;
  _query_Icon_19_2:import17.QueryList<any>;
  _text_20:any;
  _el_21:any;
  _Label_21_3:import18.Wrapper_Label;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import3.AppElement;
  _NgModel_24_4:import19.Wrapper_NgModel;
  _NgControl_24_5:any;
  _NgControlStatus_24_6:import20.Wrapper_NgControlStatus;
  _TextInput_24_7:import21.Wrapper_TextInput;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  /*private*/ _appEl_27:import3.AppElement;
  _Item_27_4:import16.Wrapper_Item;
  _ItemContent_27_5:import16.Wrapper_ItemContent;
  _query_Label_27_0:import17.QueryList<any>;
  _query_Button_27_1:import17.QueryList<any>;
  _query_Icon_27_2:import17.QueryList<any>;
  _text_28:any;
  _el_29:any;
  _Label_29_3:import18.Wrapper_Label;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  /*private*/ _appEl_32:import3.AppElement;
  _NgModel_32_4:import19.Wrapper_NgModel;
  _NgControl_32_5:any;
  _NgControlStatus_32_6:import20.Wrapper_NgControlStatus;
  _TextInput_32_7:import21.Wrapper_TextInput;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  /*private*/ _appEl_35:import3.AppElement;
  _Item_35_4:import16.Wrapper_Item;
  _ItemContent_35_5:import16.Wrapper_ItemContent;
  _query_Label_35_0:import17.QueryList<any>;
  _query_Button_35_1:import17.QueryList<any>;
  _query_Icon_35_2:import17.QueryList<any>;
  _text_36:any;
  _el_37:any;
  _Label_37_3:import18.Wrapper_Label;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  /*private*/ _appEl_40:import3.AppElement;
  _DateTime_40_4:import22.Wrapper_DateTime;
  _NG_VALUE_ACCESSOR_40_5:any[];
  _NgModel_40_6:import19.Wrapper_NgModel;
  _NgControl_40_7:any;
  _NgControlStatus_40_8:import20.Wrapper_NgControlStatus;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  /*private*/ _appEl_43:import3.AppElement;
  _Button_43_4:import23.Wrapper_Button;
  _text_44:any;
  _text_45:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_EventCreatePage0,renderType_EventCreatePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import12.Wrapper_Header(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import26.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import13.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import13.Wrapper_Navbar(this.parentInjector.get(import27.App),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import14.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import14.Wrapper_ToolbarTitle(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import28.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'New Event',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'padding','');
    this._appEl_9 = new import3.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import15.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import15.Wrapper_Content(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import27.App),this.parentInjector.get(import29.Keyboard),this.parentInjector.get(import30.NgZone),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import31.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','item item-block');
    this._appEl_11 = new import3.AppElement(11,9,this,this._el_11);
    var compView_11:any = import16.viewFactory_Item0(this.viewUtils,this.injector(11),this._appEl_11);
    this._Item_11_4 = new import16.Wrapper_Item(this.parentInjector.get(import32.Form),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_11),this.renderer,this.parentInjector.get(import33.ItemReorder,(null as any)));
    this._ItemContent_11_5 = new import16.Wrapper_ItemContent();
    this._query_Label_11_0 = new import17.QueryList<any>();
    this._query_Button_11_1 = new import17.QueryList<any>();
    this._query_Icon_11_2 = new import17.QueryList<any>();
    this._appEl_11.initComponent(this._Item_11_4.context,([] as any[]),compView_11);
    this._text_12 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_13,'stacked','');
    this._Label_13_3 = new import18.Wrapper_Label(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_13),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'Event Name',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_16,'placeholder','What\'s your event\'s name?');
    this.renderer.setElementAttribute(this._el_16,'type','text');
    this._appEl_16 = new import3.AppElement(16,11,this,this._el_16);
    var compView_16:any = import21.viewFactory_TextInput0(this.viewUtils,this.injector(16),this._appEl_16);
    this._NgModel_16_4 = new import19.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_16_5 = this._NgModel_16_4.context;
    this._NgControlStatus_16_6 = new import20.Wrapper_NgControlStatus(this._NgControl_16_5);
    this._TextInput_16_7 = new import21.Wrapper_TextInput(this.parentInjector.get(import24.Config),this.parentInjector.get(import32.Form),this._Item_11_4.context,this.parentInjector.get(import27.App),this.parentInjector.get(import34.Platform),new import25.ElementRef(this._el_16),this.renderer,this._Content_9_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_16_5);
    this._appEl_16.initComponent(this._TextInput_16_7.context,([] as any[]),compView_16);
    compView_16.create(this._TextInput_16_7.context,([] as any[]),(null as any));
    this._text_17 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_11_0.reset([this._Label_13_3.context]);
    this._Item_11_4.context.contentLabel = this._query_Label_11_0.first;
    compView_11.create(this._Item_11_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_13]),
      ([] as any[]).concat([
        this._text_12,
        this._text_15,
        this._text_17
      ]
      ),
      ([] as any[]).concat([this._el_16]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','item item-block');
    this._appEl_19 = new import3.AppElement(19,9,this,this._el_19);
    var compView_19:any = import16.viewFactory_Item0(this.viewUtils,this.injector(19),this._appEl_19);
    this._Item_19_4 = new import16.Wrapper_Item(this.parentInjector.get(import32.Form),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_19),this.renderer,this.parentInjector.get(import33.ItemReorder,(null as any)));
    this._ItemContent_19_5 = new import16.Wrapper_ItemContent();
    this._query_Label_19_0 = new import17.QueryList<any>();
    this._query_Button_19_1 = new import17.QueryList<any>();
    this._query_Icon_19_2 = new import17.QueryList<any>();
    this._appEl_19.initComponent(this._Item_19_4.context,([] as any[]),compView_19);
    this._text_20 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_21 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_21,'stacked','');
    this._Label_21_3 = new import18.Wrapper_Label(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_21),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'Price',(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_24 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_24,'placeholder','How much will guests pay?');
    this.renderer.setElementAttribute(this._el_24,'type','number');
    this._appEl_24 = new import3.AppElement(24,19,this,this._el_24);
    var compView_24:any = import21.viewFactory_TextInput0(this.viewUtils,this.injector(24),this._appEl_24);
    this._NgModel_24_4 = new import19.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_24_5 = this._NgModel_24_4.context;
    this._NgControlStatus_24_6 = new import20.Wrapper_NgControlStatus(this._NgControl_24_5);
    this._TextInput_24_7 = new import21.Wrapper_TextInput(this.parentInjector.get(import24.Config),this.parentInjector.get(import32.Form),this._Item_19_4.context,this.parentInjector.get(import27.App),this.parentInjector.get(import34.Platform),new import25.ElementRef(this._el_24),this.renderer,this._Content_9_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_24_5);
    this._appEl_24.initComponent(this._TextInput_24_7.context,([] as any[]),compView_24);
    compView_24.create(this._TextInput_24_7.context,([] as any[]),(null as any));
    this._text_25 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_19_0.reset([this._Label_21_3.context]);
    this._Item_19_4.context.contentLabel = this._query_Label_19_0.first;
    compView_19.create(this._Item_19_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_21]),
      ([] as any[]).concat([
        this._text_20,
        this._text_23,
        this._text_25
      ]
      ),
      ([] as any[]).concat([this._el_24]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_26 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_27 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','item item-block');
    this._appEl_27 = new import3.AppElement(27,9,this,this._el_27);
    var compView_27:any = import16.viewFactory_Item0(this.viewUtils,this.injector(27),this._appEl_27);
    this._Item_27_4 = new import16.Wrapper_Item(this.parentInjector.get(import32.Form),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_27),this.renderer,this.parentInjector.get(import33.ItemReorder,(null as any)));
    this._ItemContent_27_5 = new import16.Wrapper_ItemContent();
    this._query_Label_27_0 = new import17.QueryList<any>();
    this._query_Button_27_1 = new import17.QueryList<any>();
    this._query_Icon_27_2 = new import17.QueryList<any>();
    this._appEl_27.initComponent(this._Item_27_4.context,([] as any[]),compView_27);
    this._text_28 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_29 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_29,'stacked','');
    this._Label_29_3 = new import18.Wrapper_Label(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_29),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'Cost',(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_32,'placeholder','How much are you spending?');
    this.renderer.setElementAttribute(this._el_32,'type','number');
    this._appEl_32 = new import3.AppElement(32,27,this,this._el_32);
    var compView_32:any = import21.viewFactory_TextInput0(this.viewUtils,this.injector(32),this._appEl_32);
    this._NgModel_32_4 = new import19.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_32_5 = this._NgModel_32_4.context;
    this._NgControlStatus_32_6 = new import20.Wrapper_NgControlStatus(this._NgControl_32_5);
    this._TextInput_32_7 = new import21.Wrapper_TextInput(this.parentInjector.get(import24.Config),this.parentInjector.get(import32.Form),this._Item_27_4.context,this.parentInjector.get(import27.App),this.parentInjector.get(import34.Platform),new import25.ElementRef(this._el_32),this.renderer,this._Content_9_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_32_5);
    this._appEl_32.initComponent(this._TextInput_32_7.context,([] as any[]),compView_32);
    compView_32.create(this._TextInput_32_7.context,([] as any[]),(null as any));
    this._text_33 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_27_0.reset([this._Label_29_3.context]);
    this._Item_27_4.context.contentLabel = this._query_Label_27_0.first;
    compView_27.create(this._Item_27_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_29]),
      ([] as any[]).concat([
        this._text_28,
        this._text_31,
        this._text_33
      ]
      ),
      ([] as any[]).concat([this._el_32]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_35 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','item item-block');
    this._appEl_35 = new import3.AppElement(35,9,this,this._el_35);
    var compView_35:any = import16.viewFactory_Item0(this.viewUtils,this.injector(35),this._appEl_35);
    this._Item_35_4 = new import16.Wrapper_Item(this.parentInjector.get(import32.Form),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_35),this.renderer,this.parentInjector.get(import33.ItemReorder,(null as any)));
    this._ItemContent_35_5 = new import16.Wrapper_ItemContent();
    this._query_Label_35_0 = new import17.QueryList<any>();
    this._query_Button_35_1 = new import17.QueryList<any>();
    this._query_Icon_35_2 = new import17.QueryList<any>();
    this._appEl_35.initComponent(this._Item_35_4.context,([] as any[]),compView_35);
    this._text_36 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_37 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_37_3 = new import18.Wrapper_Label(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_37),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'Event Date',(null as any));
    this._text_39 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_40 = this.renderer.createElement((null as any),'ion-datetime',(null as any));
    this.renderer.setElementAttribute(this._el_40,'displayFormat','D MMM, YY');
    this.renderer.setElementAttribute(this._el_40,'pickerFormat','DD MMM YYYY');
    this._appEl_40 = new import3.AppElement(40,35,this,this._el_40);
    var compView_40:any = import22.viewFactory_DateTime0(this.viewUtils,this.injector(40),this._appEl_40);
    this._DateTime_40_4 = new import22.Wrapper_DateTime(this.parentInjector.get(import32.Form),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_40),this.renderer,this._Item_35_4.context,this.parentInjector.get(import35.PickerController,(null as any)));
    this._NG_VALUE_ACCESSOR_40_5 = [this._DateTime_40_4.context];
    this._NgModel_40_6 = new import19.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_40_5);
    this._NgControl_40_7 = this._NgModel_40_6.context;
    this._NgControlStatus_40_8 = new import20.Wrapper_NgControlStatus(this._NgControl_40_7);
    this._appEl_40.initComponent(this._DateTime_40_4.context,([] as any[]),compView_40);
    compView_40.create(this._DateTime_40_4.context,([] as any[]),(null as any));
    this._text_41 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_35_0.reset([this._Label_37_3.context]);
    this._Item_35_4.context.contentLabel = this._query_Label_35_0.first;
    compView_35.create(this._Item_35_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_37]),
      ([] as any[]).concat([
        this._text_36,
        this._text_39,
        this._text_41
      ]
      ),
      ([] as any[]).concat([this._el_40]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_42 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_43 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_43,'block','');
    this.renderer.setElementAttribute(this._el_43,'ion-button','');
    this._appEl_43 = new import3.AppElement(43,9,this,this._el_43);
    var compView_43:any = import23.viewFactory_Button0(this.viewUtils,this.injector(43),this._appEl_43);
    this._Button_43_4 = new import23.Wrapper_Button((null as any),'',this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_43),this.renderer);
    this._appEl_43.initComponent(this._Button_43_4.context,([] as any[]),compView_43);
    this._text_44 = this.renderer.createText((null as any),'\n    Create Event\n  ',(null as any));
    compView_43.create(this._Button_43_4.context,[([] as any[]).concat([this._text_44])],(null as any));
    this._text_45 = this.renderer.createText((null as any),'\n',(null as any));
    compView_9.create(this._Content_9_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_18,
        this._el_19,
        this._text_26,
        this._el_27,
        this._text_34,
        this._el_35,
        this._text_42,
        this._el_43,
        this._text_45
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_16,'ngModelChange',this.eventHandler(this._handle_ngModelChange_16_0.bind(this)));
    const subscription_0:any = this._NgModel_16_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_16_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_24,'ngModelChange',this.eventHandler(this._handle_ngModelChange_24_0.bind(this)));
    const subscription_1:any = this._NgModel_24_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_24_0.bind(this)));
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_32,'ngModelChange',this.eventHandler(this._handle_ngModelChange_32_0.bind(this)));
    const subscription_2:any = this._NgModel_32_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_32_0.bind(this)));
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_40,'ngModelChange',this.eventHandler(this._handle_ngModelChange_40_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_40,'click',this.eventHandler(this._handle_click_40_1.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_40,'keyup.space',this.eventHandler(this._handle_keyup_space_40_2.bind(this)));
    this._expr_38 = import7.UNINITIALIZED;
    const subscription_3:any = this._NgModel_40_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_40_0.bind(this)));
    this._expr_40 = import7.UNINITIALIZED;
    this._expr_41 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    this._expr_45 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_43,'click',this.eventHandler(this._handle_click_43_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2,
      subscription_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import36.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import37.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4.context; }
    if (((token === import28.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3.context; }
    if (((token === import38.Label) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Label_13_3.context; }
    if (((token === import39.NgModel) && (16 === requestNodeIndex))) { return this._NgModel_16_4.context; }
    if (((token === import40.NgControl) && (16 === requestNodeIndex))) { return this._NgControl_16_5; }
    if (((token === import41.NgControlStatus) && (16 === requestNodeIndex))) { return this._NgControlStatus_16_6.context; }
    if (((token === import42.TextInput) && (16 === requestNodeIndex))) { return this._TextInput_16_7.context; }
    if (((token === import43.Item) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Item_11_4.context; }
    if (((token === import43.ItemContent) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._ItemContent_11_5.context; }
    if (((token === import38.Label) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Label_21_3.context; }
    if (((token === import39.NgModel) && (24 === requestNodeIndex))) { return this._NgModel_24_4.context; }
    if (((token === import40.NgControl) && (24 === requestNodeIndex))) { return this._NgControl_24_5; }
    if (((token === import41.NgControlStatus) && (24 === requestNodeIndex))) { return this._NgControlStatus_24_6.context; }
    if (((token === import42.TextInput) && (24 === requestNodeIndex))) { return this._TextInput_24_7.context; }
    if (((token === import43.Item) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Item_19_4.context; }
    if (((token === import43.ItemContent) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._ItemContent_19_5.context; }
    if (((token === import38.Label) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Label_29_3.context; }
    if (((token === import39.NgModel) && (32 === requestNodeIndex))) { return this._NgModel_32_4.context; }
    if (((token === import40.NgControl) && (32 === requestNodeIndex))) { return this._NgControl_32_5; }
    if (((token === import41.NgControlStatus) && (32 === requestNodeIndex))) { return this._NgControlStatus_32_6.context; }
    if (((token === import42.TextInput) && (32 === requestNodeIndex))) { return this._TextInput_32_7.context; }
    if (((token === import43.Item) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Item_27_4.context; }
    if (((token === import43.ItemContent) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._ItemContent_27_5.context; }
    if (((token === import38.Label) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._Label_37_3.context; }
    if (((token === import44.DateTime) && (40 === requestNodeIndex))) { return this._DateTime_40_4.context; }
    if (((token === import45.NG_VALUE_ACCESSOR) && (40 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_40_5; }
    if (((token === import39.NgModel) && (40 === requestNodeIndex))) { return this._NgModel_40_6.context; }
    if (((token === import40.NgControl) && (40 === requestNodeIndex))) { return this._NgControl_40_7; }
    if (((token === import41.NgControlStatus) && (40 === requestNodeIndex))) { return this._NgControlStatus_40_8.context; }
    if (((token === import43.Item) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._Item_35_4.context; }
    if (((token === import43.ItemContent) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._ItemContent_35_5.context; }
    if (((token === import46.Button) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Button_43_4.context; }
    if (((token === import47.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Content_9_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._Content_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    if (this._Item_11_4.detectChangesInternal(this,this._el_11,throwOnChange)) { this._appEl_11.componentView.markAsCheckOnce(); }
    this._ItemContent_11_5.detectChangesInternal(this,this._el_11,throwOnChange);
    this._Label_13_3.detectChangesInternal(this,this._el_13,throwOnChange);
    const currVal_4:any = this.context.eventName;
    this._NgModel_16_4.check_model(currVal_4,throwOnChange,false);
    this._NgModel_16_4.detectChangesInternal(this,this._el_16,throwOnChange);
    this._NgControlStatus_16_6.detectChangesInternal(this,this._el_16,throwOnChange);
    const currVal_11:any = 'What\'s your event\'s name?';
    this._TextInput_16_7.check_placeholder(currVal_11,throwOnChange,false);
    const currVal_12:any = 'text';
    this._TextInput_16_7.check_type(currVal_12,throwOnChange,false);
    this._TextInput_16_7.detectChangesInternal(this,this._el_16,throwOnChange);
    if (this._Item_19_4.detectChangesInternal(this,this._el_19,throwOnChange)) { this._appEl_19.componentView.markAsCheckOnce(); }
    this._ItemContent_19_5.detectChangesInternal(this,this._el_19,throwOnChange);
    this._Label_21_3.detectChangesInternal(this,this._el_21,throwOnChange);
    const currVal_14:any = this.context.eventPrice;
    this._NgModel_24_4.check_model(currVal_14,throwOnChange,false);
    this._NgModel_24_4.detectChangesInternal(this,this._el_24,throwOnChange);
    this._NgControlStatus_24_6.detectChangesInternal(this,this._el_24,throwOnChange);
    const currVal_21:any = 'How much will guests pay?';
    this._TextInput_24_7.check_placeholder(currVal_21,throwOnChange,false);
    const currVal_22:any = 'number';
    this._TextInput_24_7.check_type(currVal_22,throwOnChange,false);
    this._TextInput_24_7.detectChangesInternal(this,this._el_24,throwOnChange);
    if (this._Item_27_4.detectChangesInternal(this,this._el_27,throwOnChange)) { this._appEl_27.componentView.markAsCheckOnce(); }
    this._ItemContent_27_5.detectChangesInternal(this,this._el_27,throwOnChange);
    this._Label_29_3.detectChangesInternal(this,this._el_29,throwOnChange);
    const currVal_24:any = this.context.eventCost;
    this._NgModel_32_4.check_model(currVal_24,throwOnChange,false);
    this._NgModel_32_4.detectChangesInternal(this,this._el_32,throwOnChange);
    this._NgControlStatus_32_6.detectChangesInternal(this,this._el_32,throwOnChange);
    const currVal_31:any = 'How much are you spending?';
    this._TextInput_32_7.check_placeholder(currVal_31,throwOnChange,false);
    const currVal_32:any = 'number';
    this._TextInput_32_7.check_type(currVal_32,throwOnChange,false);
    this._TextInput_32_7.detectChangesInternal(this,this._el_32,throwOnChange);
    if (this._Item_35_4.detectChangesInternal(this,this._el_35,throwOnChange)) { this._appEl_35.componentView.markAsCheckOnce(); }
    this._ItemContent_35_5.detectChangesInternal(this,this._el_35,throwOnChange);
    this._Label_37_3.detectChangesInternal(this,this._el_37,throwOnChange);
    const currVal_36:any = 'D MMM, YY';
    this._DateTime_40_4.check_displayFormat(currVal_36,throwOnChange,false);
    const currVal_37:any = 'DD MMM YYYY';
    this._DateTime_40_4.check_pickerFormat(currVal_37,throwOnChange,false);
    this._DateTime_40_4.detectChangesInternal(this,this._el_40,throwOnChange);
    const currVal_39:any = this.context.eventDate;
    this._NgModel_40_6.check_model(currVal_39,throwOnChange,false);
    this._NgModel_40_6.detectChangesInternal(this,this._el_40,throwOnChange);
    this._NgControlStatus_40_8.detectChangesInternal(this,this._el_40,throwOnChange);
    const currVal_47:any = '';
    this._Button_43_4.check_block(currVal_47,throwOnChange,false);
    if (this._Button_43_4.detectChangesInternal(this,this._el_43,throwOnChange)) { this._appEl_43.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_11_1.dirty) {
        this._query_Button_11_1.reset(([] as any[]));
        this._Item_11_4.context._buttons = this._query_Button_11_1;
        this._query_Button_11_1.notifyOnChanges();
      }
      if (this._query_Icon_11_2.dirty) {
        this._query_Icon_11_2.reset(([] as any[]));
        this._Item_11_4.context._icons = this._query_Icon_11_2;
        this._query_Icon_11_2.notifyOnChanges();
      }
      if (this._query_Button_19_1.dirty) {
        this._query_Button_19_1.reset(([] as any[]));
        this._Item_19_4.context._buttons = this._query_Button_19_1;
        this._query_Button_19_1.notifyOnChanges();
      }
      if (this._query_Icon_19_2.dirty) {
        this._query_Icon_19_2.reset(([] as any[]));
        this._Item_19_4.context._icons = this._query_Icon_19_2;
        this._query_Icon_19_2.notifyOnChanges();
      }
      if (this._query_Button_27_1.dirty) {
        this._query_Button_27_1.reset(([] as any[]));
        this._Item_27_4.context._buttons = this._query_Button_27_1;
        this._query_Button_27_1.notifyOnChanges();
      }
      if (this._query_Icon_27_2.dirty) {
        this._query_Icon_27_2.reset(([] as any[]));
        this._Item_27_4.context._icons = this._query_Icon_27_2;
        this._query_Icon_27_2.notifyOnChanges();
      }
      if (this._query_Button_35_1.dirty) {
        this._query_Button_35_1.reset(([] as any[]));
        this._Item_35_4.context._buttons = this._query_Button_35_1;
        this._query_Button_35_1.notifyOnChanges();
      }
      if (this._query_Icon_35_2.dirty) {
        this._query_Icon_35_2.reset(([] as any[]));
        this._Item_35_4.context._icons = this._query_Icon_35_2;
        this._query_Icon_35_2.notifyOnChanges();
      }
      this._TextInput_16_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_11_4.context.ngAfterContentInit(); }
      this._TextInput_24_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_19_4.context.ngAfterContentInit(); }
      this._TextInput_32_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_27_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._DateTime_40_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_35_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_43_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_9_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._NgControlStatus_16_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_16,'ng-untouched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatus_16_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_16,'ng-touched',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_16_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_16,'ng-pristine',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_16_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_16,'ng-dirty',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_16_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_16,'ng-valid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_16_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_16,'ng-invalid',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_15:any = this._NgControlStatus_24_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_24,'ng-untouched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_24_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_24,'ng-touched',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_24_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_24,'ng-pristine',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_24_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_24,'ng-dirty',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_24_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_24,'ng-valid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_24_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_24,'ng-invalid',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_25:any = this._NgControlStatus_32_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_32,'ng-untouched',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_32_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_32,'ng-touched',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_32_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_32,'ng-pristine',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_32_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_32,'ng-dirty',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_32_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_32,'ng-valid',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_32_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_32,'ng-invalid',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_38:any = this._DateTime_40_4.context._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_40,'datetime-disabled',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_40:any = this._NgControlStatus_40_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_40,'ng-untouched',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_41:any = this._NgControlStatus_40_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setElementClass(this._el_40,'ng-touched',currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_42:any = this._NgControlStatus_40_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementClass(this._el_40,'ng-pristine',currVal_42);
      this._expr_42 = currVal_42;
    }
    const currVal_43:any = this._NgControlStatus_40_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setElementClass(this._el_40,'ng-dirty',currVal_43);
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = this._NgControlStatus_40_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementClass(this._el_40,'ng-valid',currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_45:any = this._NgControlStatus_40_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementClass(this._el_40,'ng-invalid',currVal_45);
      this._expr_45 = currVal_45;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._NgModel_16_4.context.ngOnDestroy();
    this._TextInput_16_7.context.ngOnDestroy();
    this._NgModel_24_4.context.ngOnDestroy();
    this._TextInput_24_7.context.ngOnDestroy();
    this._NgModel_32_4.context.ngOnDestroy();
    this._TextInput_32_7.context.ngOnDestroy();
    this._DateTime_40_4.context.ngOnDestroy();
    this._NgModel_40_6.context.ngOnDestroy();
    this._Content_9_4.context.ngOnDestroy();
  }
  private _handle_ngModelChange_16_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.eventName = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_24_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.eventPrice = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_32_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.eventCost = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_40_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.eventDate = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_40_1($event:any):boolean {
    this._appEl_40.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_40_4.context._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_40_2($event:any):boolean {
    this._appEl_40.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_40_4.context._keyup()) !== false);
    return (true && pd_0);
  }
  private _handle_click_43_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.createEvent(this.context.eventName,this.context.eventDate,this.context.eventPrice,this.context.eventCost)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_EventCreatePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.EventCreatePage> {
  if ((renderType_EventCreatePage === (null as any))) { (renderType_EventCreatePage = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_EventCreatePage,{})); }
  return new _View_EventCreatePage0(viewUtils,parentInjector,declarationEl);
}