/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './dish-detail';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from '../../providers/dish-data';
import * as import11 from '../../providers/profile-data';
import * as import12 from 'ionic-angular/components/alert/alert';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import20 from '@angular/core/src/linker/query_list';
import * as import21 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import24 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/fab/fab.ngfactory';
import * as import26 from 'ionic-angular/config/config';
import * as import27 from '@angular/core/src/linker/element_ref';
import * as import28 from 'ionic-angular/navigation/view-controller';
import * as import29 from 'ionic-angular/components/app/app';
import * as import30 from 'ionic-angular/components/menu/menu-controller';
import * as import31 from 'ionic-angular/components/toolbar/toolbar';
import * as import32 from 'ionic-angular/util/keyboard';
import * as import33 from '@angular/core/src/zone/ng_zone';
import * as import34 from 'ionic-angular/components/tabs/tabs';
import * as import35 from '@angular/core/src/linker/template_ref';
import * as import36 from 'ionic-angular/components/icon/icon';
import * as import37 from 'ionic-angular/components/button/button';
import * as import38 from 'ionic-angular/components/menu/menu-toggle';
import * as import39 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import40 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import41 from 'ionic-angular/components/navbar/navbar';
import * as import42 from '@angular/common/src/directives/ng_if';
import * as import43 from 'ionic-angular/components/fab/fab';
import * as import44 from 'ionic-angular/components/content/content';
import * as import45 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import46 from 'ionic-angular/util/form';
import * as import47 from 'ionic-angular/components/item/item-reorder';
import * as import48 from 'ionic-angular/components/item/item';
import * as import49 from '@angular/core/src/security';
import * as import50 from '../../node_modules/ionic-angular/components/avatar/avatar.ngfactory';
import * as import51 from 'ionic-angular/components/avatar/avatar';
export class Wrapper_DishDetailPage {
  context:import0.DishDetailPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this.changed = false;
    this.context = new import0.DishDetailPage(p0,p1,p2,p3,p4);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_DishDetailPage_Host:import2.RenderComponentType = (null as any);
class _View_DishDetailPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _DishDetailPage_0_4:Wrapper_DishDetailPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_DishDetailPage_Host0,renderType_DishDetailPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-dish-detail',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_DishDetailPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DishDetailPage_0_4 = new Wrapper_DishDetailPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams),this.parentInjector.get(import10.DishData),this.parentInjector.get(import11.ProfileData),this.parentInjector.get(import12.AlertController));
    this._appEl_0.initComponent(this._DishDetailPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._DishDetailPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.DishDetailPage) && (0 === requestNodeIndex))) { return this._DishDetailPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DishDetailPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DishDetailPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_DishDetailPage_Host === (null as any))) { (renderType_DishDetailPage_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_DishDetailPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const DishDetailPageNgFactory:import14.ComponentFactory<import0.DishDetailPage> = new import14.ComponentFactory<import0.DishDetailPage>('page-dish-detail',viewFactory_DishDetailPage_Host0,import0.DishDetailPage);
const styles_DishDetailPage:any[] = ([] as any[]);
var renderType_DishDetailPage:import2.RenderComponentType = (null as any);
class _View_DishDetailPage0 extends import1.AppView<import0.DishDetailPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import15.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import16.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _Button_5_4:import17.Wrapper_Button;
  _MenuToggle_5_5:import18.Wrapper_MenuToggle;
  _ToolbarItem_5_6:import19.Wrapper_ToolbarItem;
  _query_Button_5_0:import20.QueryList<any>;
  _text_6:any;
  _el_7:any;
  _Icon_7_3:import21.Wrapper_Icon;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _ToolbarItem_10_3:import19.Wrapper_ToolbarItem;
  _query_Button_10_0:import20.QueryList<any>;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import3.AppElement;
  _Button_12_4:import17.Wrapper_Button;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _Icon_15_3:import21.Wrapper_Icon;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  /*private*/ _appEl_19:import3.AppElement;
  _ToolbarTitle_19_4:import22.Wrapper_ToolbarTitle;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import3.AppElement;
  _Content_24_4:import23.Wrapper_Content;
  _text_25:any;
  _anchor_26:any;
  /*private*/ _appEl_26:import3.AppElement;
  _TemplateRef_26_5:any;
  _NgIf_26_6:import24.Wrapper_NgIf;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import3.AppElement;
  _FabContainer_28_4:import25.Wrapper_FabContainer;
  _query_FabButton_28_0:import20.QueryList<any>;
  _query_FabList_28_1:import20.QueryList<any>;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import3.AppElement;
  _FabButton_30_4:import25.Wrapper_FabButton;
  _text_31:any;
  _el_32:any;
  _Icon_32_3:import21.Wrapper_Icon;
  _text_33:any;
  _text_34:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_17:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_DishDetailPage0,renderType_DishDetailPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import15.Wrapper_Header(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import28.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this.renderer.setElementAttribute(this._el_3,'color','primary');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import16.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import16.Wrapper_Navbar(this.parentInjector.get(import29.App),this.parentInjector.get(import28.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_5,'ion-button','');
    this.renderer.setElementAttribute(this._el_5,'menuToggle','');
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import17.viewFactory_Button0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Button_5_4 = new import17.Wrapper_Button('','',this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_5),this.renderer);
    this._MenuToggle_5_5 = new import18.Wrapper_MenuToggle(this.parentInjector.get(import30.MenuController),new import27.ElementRef(this._el_5),this.parentInjector.get(import28.ViewController,(null as any)),this._Navbar_3_4.context);
    this._ToolbarItem_5_6 = new import19.Wrapper_ToolbarItem(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import31.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._query_Button_5_0 = new import20.QueryList<any>();
    this._appEl_5.initComponent(this._Button_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_7,'name','menu');
    this.renderer.setElementAttribute(this._el_7,'role','img');
    this._Icon_7_3 = new import21.Wrapper_Icon(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_7),this.renderer);
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_5.create(this._Button_5_4.context,[([] as any[]).concat([
        this._text_6,
        this._el_7,
        this._text_8
      ]
    )],(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_10,'start','');
    this._ToolbarItem_10_3 = new import19.Wrapper_ToolbarItem(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import31.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._query_Button_10_0 = new import20.QueryList<any>();
    this._text_11 = this.renderer.createText(this._el_10,'\n      ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'button',(null as any));
    this.renderer.setElementAttribute(this._el_12,'ion-button','');
    this._appEl_12 = new import3.AppElement(12,10,this,this._el_12);
    var compView_12:any = import17.viewFactory_Button0(this.viewUtils,this.injector(12),this._appEl_12);
    this._Button_12_4 = new import17.Wrapper_Button((null as any),'',this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_12),this.renderer);
    this._appEl_12.initComponent(this._Button_12_4.context,([] as any[]),compView_12);
    this._text_13 = this.renderer.createText((null as any),' ',(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_15 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_15,'name','share');
    this.renderer.setElementAttribute(this._el_15,'role','img');
    this._Icon_15_3 = new import21.Wrapper_Icon(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_15),this.renderer);
    this._text_16 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_12.create(this._Button_12_4.context,[([] as any[]).concat([
        this._text_13,
        this._text_14,
        this._el_15,
        this._text_16
      ]
    )],(null as any));
    this._text_17 = this.renderer.createText(this._el_10,'\n    ',(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_19 = new import3.AppElement(19,3,this,this._el_19);
    var compView_19:any = import22.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(19),this._appEl_19);
    this._ToolbarTitle_19_4 = new import22.Wrapper_ToolbarTitle(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_19),this.renderer,this.parentInjector.get(import31.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_19.initComponent(this._ToolbarTitle_19_4.context,([] as any[]),compView_19);
    this._text_20 = this.renderer.createText((null as any),'',(null as any));
    compView_19.create(this._ToolbarTitle_19_4.context,[([] as any[]).concat([this._text_20])],(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]).concat([this._el_5]),
      ([] as any[]).concat([this._el_10]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_4,
        this._text_9,
        this._text_18,
        this._el_19,
        this._text_21
      ]
      )
    ]
    ,(null as any));
    this._text_22 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_23 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_24 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_24,'padding','');
    this._appEl_24 = new import3.AppElement(24,(null as any),this,this._el_24);
    var compView_24:any = import23.viewFactory_Content0(this.viewUtils,this.injector(24),this._appEl_24);
    this._Content_24_4 = new import23.Wrapper_Content(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_24),this.renderer,this.parentInjector.get(import29.App),this.parentInjector.get(import32.Keyboard),this.parentInjector.get(import33.NgZone),this.parentInjector.get(import28.ViewController,(null as any)),this.parentInjector.get(import34.Tabs,(null as any)));
    this._appEl_24.initComponent(this._Content_24_4.context,([] as any[]),compView_24);
    this._text_25 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._anchor_26 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_26 = new import3.AppElement(26,24,this,this._anchor_26);
    this._TemplateRef_26_5 = new import35.TemplateRef_(this._appEl_26,viewFactory_DishDetailPage1);
    this._NgIf_26_6 = new import24.Wrapper_NgIf(this._appEl_26.vcRef,this._TemplateRef_26_5);
    this._text_27 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_28 = this.renderer.createElement((null as any),'ion-fab',(null as any));
    this.renderer.setElementAttribute(this._el_28,'bottom','');
    this.renderer.setElementAttribute(this._el_28,'right','');
    this._appEl_28 = new import3.AppElement(28,24,this,this._el_28);
    var compView_28:any = import25.viewFactory_FabContainer0(this.viewUtils,this.injector(28),this._appEl_28);
    this._FabContainer_28_4 = new import25.Wrapper_FabContainer(new import27.ElementRef(this._el_28));
    this._query_FabButton_28_0 = new import20.QueryList<any>();
    this._query_FabList_28_1 = new import20.QueryList<any>();
    this._appEl_28.initComponent(this._FabContainer_28_4.context,([] as any[]),compView_28);
    this._text_29 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_30,'color','primary');
    this.renderer.setElementAttribute(this._el_30,'ion-fab','');
    this._appEl_30 = new import3.AppElement(30,28,this,this._el_30);
    var compView_30:any = import25.viewFactory_FabButton0(this.viewUtils,this.injector(30),this._appEl_30);
    this._FabButton_30_4 = new import25.Wrapper_FabButton(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_30),this.renderer);
    this._appEl_30.initComponent(this._FabButton_30_4.context,([] as any[]),compView_30);
    this._text_31 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_32,'name','basket');
    this.renderer.setElementAttribute(this._el_32,'role','img');
    this._Icon_32_3 = new import21.Wrapper_Icon(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_32),this.renderer);
      compView_30.create(this._FabButton_30_4.context,[([] as any[]).concat([
        this._text_31,
        this._el_32
      ]
    )],(null as any));
    this._text_33 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_FabButton_28_0.reset([this._FabButton_30_4.context]);
    this._FabContainer_28_4.context._mainButton = this._query_FabButton_28_0.first;
      compView_28.create(this._FabContainer_28_4.context,[([] as any[]).concat([
        this._text_29,
        this._el_30,
        this._text_33
      ]
    )],(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n',(null as any));
    compView_24.create(this._Content_24_4.context,[
      ([] as any[]).concat([this._el_28]),
      ([] as any[]).concat([
        this._text_25,
        this._appEl_26,
        this._text_27,
        this._text_34
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_30,'click',this.eventHandler(this._handle_click_30_0.bind(this)));
    this._expr_17 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._anchor_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import36.Icon) && (7 === requestNodeIndex))) { return this._Icon_7_3.context; }
    if (((token === import37.Button) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Button_5_4.context; }
    if (((token === import38.MenuToggle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._MenuToggle_5_5.context; }
    if (((token === import39.ToolbarItem) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ToolbarItem_5_6.context; }
    if (((token === import36.Icon) && (15 === requestNodeIndex))) { return this._Icon_15_3.context; }
    if (((token === import37.Button) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Button_12_4.context; }
    if (((token === import39.ToolbarItem) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._ToolbarItem_10_3.context; }
    if (((token === import40.ToolbarTitle) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._ToolbarTitle_19_4.context; }
    if (((token === import41.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Navbar_3_4.context; }
    if (((token === import31.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Header_1_3.context; }
    if (((token === import35.TemplateRef) && (26 === requestNodeIndex))) { return this._TemplateRef_26_5; }
    if (((token === import42.NgIf) && (26 === requestNodeIndex))) { return this._NgIf_26_6.context; }
    if (((token === import36.Icon) && (32 === requestNodeIndex))) { return this._Icon_32_3.context; }
    if (((token === import43.FabButton) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._FabButton_30_4.context; }
    if (((token === import43.FabContainer) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._FabContainer_28_4.context; }
    if (((token === import44.Content) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Content_24_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    const currVal_0:any = 'primary';
    this._Navbar_3_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._Button_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    const currVal_4:any = '';
    this._MenuToggle_5_5.check_menuToggle(currVal_4,throwOnChange,false);
    this._MenuToggle_5_5.detectChangesInternal(this,this._el_5,throwOnChange);
    this._ToolbarItem_5_6.detectChangesInternal(this,this._el_5,throwOnChange);
    const currVal_6:any = 'menu';
    this._Icon_7_3.check_name(currVal_6,throwOnChange,false);
    this._Icon_7_3.detectChangesInternal(this,this._el_7,throwOnChange);
    this._ToolbarItem_10_3.detectChangesInternal(this,this._el_10,throwOnChange);
    if (this._Button_12_4.detectChangesInternal(this,this._el_12,throwOnChange)) { this._appEl_12.componentView.markAsCheckOnce(); }
    const currVal_8:any = 'share';
    this._Icon_15_3.check_name(currVal_8,throwOnChange,false);
    this._Icon_15_3.detectChangesInternal(this,this._el_15,throwOnChange);
    if (this._ToolbarTitle_19_4.detectChangesInternal(this,this._el_19,throwOnChange)) { this._appEl_19.componentView.markAsCheckOnce(); }
    if (this._Content_24_4.detectChangesInternal(this,this._el_24,throwOnChange)) { this._appEl_24.componentView.markAsCheckOnce(); }
    const currVal_12:any = this.context.currentDish;
    this._NgIf_26_6.check_ngIf(currVal_12,throwOnChange,false);
    this._NgIf_26_6.detectChangesInternal(this,this._anchor_26,throwOnChange);
    this._FabContainer_28_4.detectChangesInternal(this,this._el_28,throwOnChange);
    const currVal_15:any = 'primary';
    this._FabButton_30_4.check_color(currVal_15,throwOnChange,false);
    if (this._FabButton_30_4.detectChangesInternal(this,this._el_30,throwOnChange)) { this._appEl_30.componentView.markAsCheckOnce(); }
    const currVal_16:any = 'basket';
    this._Icon_32_3.check_name(currVal_16,throwOnChange,false);
    this._Icon_32_3.detectChangesInternal(this,this._el_32,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_5_0.dirty) {
        this._query_Button_5_0.reset([this._Button_5_4.context]);
        this._ToolbarItem_5_6.context._buttons = this._query_Button_5_0;
        this._query_Button_5_0.notifyOnChanges();
      }
      if (this._query_Button_10_0.dirty) {
        this._query_Button_10_0.reset([this._Button_12_4.context]);
        this._ToolbarItem_10_3.context._buttons = this._query_Button_10_0;
        this._query_Button_10_0.notifyOnChanges();
      }
      if (this._query_FabList_28_1.dirty) {
        this._query_FabList_28_1.reset(([] as any[]));
        this._FabContainer_28_4.context._fabLists = this._query_FabList_28_1;
        this._query_FabList_28_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_5_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_12_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._FabContainer_28_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._MenuToggle_5_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_5,'hidden',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_7:any = this._Icon_7_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_7,'hide',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_9:any = this._Icon_15_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_15,'hide',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = import4.interpolate(1,'',this.context.currentDish.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setText(this._text_20,currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._Content_24_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_24,'statusbar-padding',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_14:any = (this.context.currentDish.portionsLeftNumber <= 0);
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementProperty(this._el_30,'disabled',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_17:any = this._Icon_32_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_32,'hide',currVal_17);
      this._expr_17 = currVal_17;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_7_3.context.ngOnDestroy();
    this._Icon_15_3.context.ngOnDestroy();
    this._Icon_32_3.context.ngOnDestroy();
    this._FabContainer_28_4.context.ngOnDestroy();
    this._Content_24_4.context.ngOnDestroy();
  }
  private _handle_click_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_5_5.context.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_click_30_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.order()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_DishDetailPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.DishDetailPage> {
  if ((renderType_DishDetailPage === (null as any))) { (renderType_DishDetailPage = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_DishDetailPage,{})); }
  return new _View_DishDetailPage0(viewUtils,parentInjector,declarationEl);
}
class _View_DishDetailPage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import3.AppElement;
  _Item_6_4:import45.Wrapper_Item;
  _ItemContent_6_5:import45.Wrapper_ItemContent;
  _query_Label_6_0:import20.QueryList<any>;
  _query_Button_6_1:import20.QueryList<any>;
  _query_Icon_6_2:import20.QueryList<any>;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import3.AppElement;
  _Item_13_4:import45.Wrapper_Item;
  _ItemContent_13_5:import45.Wrapper_ItemContent;
  _query_Label_13_0:import20.QueryList<any>;
  _query_Button_13_1:import20.QueryList<any>;
  _query_Icon_13_2:import20.QueryList<any>;
  _text_14:any;
  _el_15:any;
  _Icon_15_3:import21.Wrapper_Icon;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  /*private*/ _appEl_18:import3.AppElement;
  _Item_18_4:import45.Wrapper_Item;
  _ItemContent_18_5:import45.Wrapper_ItemContent;
  _query_Label_18_0:import20.QueryList<any>;
  _query_Button_18_1:import20.QueryList<any>;
  _query_Icon_18_2:import20.QueryList<any>;
  _text_19:any;
  _el_20:any;
  _Icon_20_3:import21.Wrapper_Icon;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _Item_23_4:import45.Wrapper_Item;
  _ItemContent_23_5:import45.Wrapper_ItemContent;
  _query_Label_23_0:import20.QueryList<any>;
  _query_Button_23_1:import20.QueryList<any>;
  _query_Icon_23_2:import20.QueryList<any>;
  _text_24:any;
  _el_25:any;
  _Icon_25_3:import21.Wrapper_Icon;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _anchor_30:any;
  /*private*/ _appEl_30:import3.AppElement;
  _TemplateRef_30_5:any;
  _NgIf_30_6:import24.Wrapper_NgIf;
  _text_31:any;
  _text_32:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_DishDetailPage1,renderType_DishDetailPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','selection');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._text_2 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_0,'img',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n\n      ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_0,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','item item-block');
    this._appEl_6 = new import3.AppElement(6,0,this,this._el_6);
    var compView_6:any = import45.viewFactory_Item0(this.viewUtils,this.injector(6),this._appEl_6);
    this._Item_6_4 = new import45.Wrapper_Item(this.parent.parentInjector.get(import46.Form),this.parent.parentInjector.get(import26.Config),new import27.ElementRef(this._el_6),this.renderer,this.parent.parentInjector.get(import47.ItemReorder,(null as any)));
    this._ItemContent_6_5 = new import45.Wrapper_ItemContent();
    this._query_Label_6_0 = new import20.QueryList<any>();
    this._query_Button_6_1 = new import20.QueryList<any>();
    this._query_Icon_6_2 = new import20.QueryList<any>();
    this._appEl_6.initComponent(this._Item_6_4.context,([] as any[]),compView_6);
    this._text_7 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','item-description');
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_6_0.reset(([] as any[]));
    this._Item_6_4.context.contentLabel = this._query_Label_6_0.first;
    compView_6.create(this._Item_6_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_7,
        this._el_8,
        this._text_10
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_11 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_0,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','item item-block');
    this._appEl_13 = new import3.AppElement(13,0,this,this._el_13);
    var compView_13:any = import45.viewFactory_Item0(this.viewUtils,this.injector(13),this._appEl_13);
    this._Item_13_4 = new import45.Wrapper_Item(this.parent.parentInjector.get(import46.Form),this.parent.parentInjector.get(import26.Config),new import27.ElementRef(this._el_13),this.renderer,this.parent.parentInjector.get(import47.ItemReorder,(null as any)));
    this._ItemContent_13_5 = new import45.Wrapper_ItemContent();
    this._query_Label_13_0 = new import20.QueryList<any>();
    this._query_Button_13_1 = new import20.QueryList<any>();
    this._query_Icon_13_2 = new import20.QueryList<any>();
    this._appEl_13.initComponent(this._Item_13_4.context,([] as any[]),compView_13);
    this._text_14 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_15 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_15,'item-left','');
    this.renderer.setElementAttribute(this._el_15,'name','restaurant');
    this.renderer.setElementAttribute(this._el_15,'role','img');
    this._Icon_15_3 = new import21.Wrapper_Icon(this.parent.parentInjector.get(import26.Config),new import27.ElementRef(this._el_15),this.renderer);
    this._text_16 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_13_0.reset(([] as any[]));
    this._Item_13_4.context.contentLabel = this._query_Label_13_0.first;
    compView_13.create(this._Item_13_4.context,[
      ([] as any[]).concat([this._el_15]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_14,
        this._text_16
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_17 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_0,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','item item-block');
    this._appEl_18 = new import3.AppElement(18,0,this,this._el_18);
    var compView_18:any = import45.viewFactory_Item0(this.viewUtils,this.injector(18),this._appEl_18);
    this._Item_18_4 = new import45.Wrapper_Item(this.parent.parentInjector.get(import46.Form),this.parent.parentInjector.get(import26.Config),new import27.ElementRef(this._el_18),this.renderer,this.parent.parentInjector.get(import47.ItemReorder,(null as any)));
    this._ItemContent_18_5 = new import45.Wrapper_ItemContent();
    this._query_Label_18_0 = new import20.QueryList<any>();
    this._query_Button_18_1 = new import20.QueryList<any>();
    this._query_Icon_18_2 = new import20.QueryList<any>();
    this._appEl_18.initComponent(this._Item_18_4.context,([] as any[]),compView_18);
    this._text_19 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_20 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_20,'item-left','');
    this.renderer.setElementAttribute(this._el_20,'name','pricetag');
    this.renderer.setElementAttribute(this._el_20,'role','img');
    this._Icon_20_3 = new import21.Wrapper_Icon(this.parent.parentInjector.get(import26.Config),new import27.ElementRef(this._el_20),this.renderer);
    this._text_21 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_18_0.reset(([] as any[]));
    this._Item_18_4.context.contentLabel = this._query_Label_18_0.first;
    compView_18.create(this._Item_18_4.context,[
      ([] as any[]).concat([this._el_20]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_19,
        this._text_21
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_0,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','item item-block');
    this._appEl_23 = new import3.AppElement(23,0,this,this._el_23);
    var compView_23:any = import45.viewFactory_Item0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Item_23_4 = new import45.Wrapper_Item(this.parent.parentInjector.get(import46.Form),this.parent.parentInjector.get(import26.Config),new import27.ElementRef(this._el_23),this.renderer,this.parent.parentInjector.get(import47.ItemReorder,(null as any)));
    this._ItemContent_23_5 = new import45.Wrapper_ItemContent();
    this._query_Label_23_0 = new import20.QueryList<any>();
    this._query_Button_23_1 = new import20.QueryList<any>();
    this._query_Icon_23_2 = new import20.QueryList<any>();
    this._appEl_23.initComponent(this._Item_23_4.context,([] as any[]),compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_25,'item-left','');
    this.renderer.setElementAttribute(this._el_25,'name','time');
    this.renderer.setElementAttribute(this._el_25,'role','img');
    this._Icon_25_3 = new import21.Wrapper_Icon(this.parent.parentInjector.get(import26.Config),new import27.ElementRef(this._el_25),this.renderer);
    this._text_26 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_23_0.reset(([] as any[]));
    this._Item_23_4.context.contentLabel = this._query_Label_23_0.first;
    compView_23.create(this._Item_23_4.context,[
      ([] as any[]).concat([this._el_25]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_24,
        this._text_26
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_27 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._text_28 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._text_29 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._anchor_30 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_30 = new import3.AppElement(30,0,this,this._anchor_30);
    this._TemplateRef_30_5 = new import35.TemplateRef_(this._appEl_30,viewFactory_DishDetailPage2);
    this._NgIf_30_6 = new import24.Wrapper_NgIf(this._appEl_30.vcRef,this._TemplateRef_30_5);
    this._text_31 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._text_32 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._anchor_30,
      this._text_31,
      this._text_32
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import48.Item) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Item_6_4.context; }
    if (((token === import48.ItemContent) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ItemContent_6_5.context; }
    if (((token === import36.Icon) && (15 === requestNodeIndex))) { return this._Icon_15_3.context; }
    if (((token === import48.Item) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Item_13_4.context; }
    if (((token === import48.ItemContent) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._ItemContent_13_5.context; }
    if (((token === import36.Icon) && (20 === requestNodeIndex))) { return this._Icon_20_3.context; }
    if (((token === import48.Item) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Item_18_4.context; }
    if (((token === import48.ItemContent) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._ItemContent_18_5.context; }
    if (((token === import36.Icon) && (25 === requestNodeIndex))) { return this._Icon_25_3.context; }
    if (((token === import48.Item) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Item_23_4.context; }
    if (((token === import48.ItemContent) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._ItemContent_23_5.context; }
    if (((token === import35.TemplateRef) && (30 === requestNodeIndex))) { return this._TemplateRef_30_5; }
    if (((token === import42.NgIf) && (30 === requestNodeIndex))) { return this._NgIf_30_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_6_4.detectChangesInternal(this,this._el_6,throwOnChange)) { this._appEl_6.componentView.markAsCheckOnce(); }
    this._ItemContent_6_5.detectChangesInternal(this,this._el_6,throwOnChange);
    if (this._Item_13_4.detectChangesInternal(this,this._el_13,throwOnChange)) { this._appEl_13.componentView.markAsCheckOnce(); }
    this._ItemContent_13_5.detectChangesInternal(this,this._el_13,throwOnChange);
    const currVal_2:any = 'restaurant';
    this._Icon_15_3.check_name(currVal_2,throwOnChange,false);
    this._Icon_15_3.detectChangesInternal(this,this._el_15,throwOnChange);
    if (this._Item_18_4.detectChangesInternal(this,this._el_18,throwOnChange)) { this._appEl_18.componentView.markAsCheckOnce(); }
    this._ItemContent_18_5.detectChangesInternal(this,this._el_18,throwOnChange);
    const currVal_5:any = 'pricetag';
    this._Icon_20_3.check_name(currVal_5,throwOnChange,false);
    this._Icon_20_3.detectChangesInternal(this,this._el_20,throwOnChange);
    if (this._Item_23_4.detectChangesInternal(this,this._el_23,throwOnChange)) { this._appEl_23.componentView.markAsCheckOnce(); }
    this._ItemContent_23_5.detectChangesInternal(this,this._el_23,throwOnChange);
    const currVal_8:any = 'time';
    this._Icon_25_3.check_name(currVal_8,throwOnChange,false);
    this._Icon_25_3.detectChangesInternal(this,this._el_25,throwOnChange);
    const currVal_11:any = this.parent.context.seller;
    this._NgIf_30_6.check_ngIf(currVal_11,throwOnChange,false);
    this._NgIf_30_6.detectChangesInternal(this,this._anchor_30,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_6_1.dirty) {
        this._query_Button_6_1.reset(([] as any[]));
        this._Item_6_4.context._buttons = this._query_Button_6_1;
        this._query_Button_6_1.notifyOnChanges();
      }
      if (this._query_Icon_6_2.dirty) {
        this._query_Icon_6_2.reset(([] as any[]));
        this._Item_6_4.context._icons = this._query_Icon_6_2;
        this._query_Icon_6_2.notifyOnChanges();
      }
      if (this._query_Button_13_1.dirty) {
        this._query_Button_13_1.reset(([] as any[]));
        this._Item_13_4.context._buttons = this._query_Button_13_1;
        this._query_Button_13_1.notifyOnChanges();
      }
      if (this._query_Icon_13_2.dirty) {
        this._query_Icon_13_2.reset([this._Icon_15_3.context]);
        this._Item_13_4.context._icons = this._query_Icon_13_2;
        this._query_Icon_13_2.notifyOnChanges();
      }
      if (this._query_Button_18_1.dirty) {
        this._query_Button_18_1.reset(([] as any[]));
        this._Item_18_4.context._buttons = this._query_Button_18_1;
        this._query_Button_18_1.notifyOnChanges();
      }
      if (this._query_Icon_18_2.dirty) {
        this._query_Icon_18_2.reset([this._Icon_20_3.context]);
        this._Item_18_4.context._icons = this._query_Icon_18_2;
        this._query_Icon_18_2.notifyOnChanges();
      }
      if (this._query_Button_23_1.dirty) {
        this._query_Button_23_1.reset(([] as any[]));
        this._Item_23_4.context._buttons = this._query_Button_23_1;
        this._query_Button_23_1.notifyOnChanges();
      }
      if (this._query_Icon_23_2.dirty) {
        this._query_Icon_23_2.reset([this._Icon_25_3.context]);
        this._Item_23_4.context._icons = this._query_Icon_23_2;
        this._query_Icon_23_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_6_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_13_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_18_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_23_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.currentDish.photo,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'src',this.viewUtils.sanitizer.sanitize(import49.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.parent.context.currentDish.description,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_9,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_3:any = this._Icon_15_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_15,'hide',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(1,'\n        ',this.parent.context.currentDish.portionsLeftNumber,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_16,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_20_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_20,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = import4.interpolate(1,'\n        ',this.parent.context.currentDish.price,'€\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_21,currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_9:any = this._Icon_25_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_25,'hide',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = import4.interpolate(3,'\n        ',this.parent.context.currentDish.dateString,' : ',this.parent.context.currentDish.timeStartString,' - ',this.parent.context.currentDish.timeEndString,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setText(this._text_26,currVal_10);
      this._expr_10 = currVal_10;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_15_3.context.ngOnDestroy();
    this._Icon_20_3.context.ngOnDestroy();
    this._Icon_25_3.context.ngOnDestroy();
  }
}
function viewFactory_DishDetailPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_DishDetailPage1(viewUtils,parentInjector,declarationEl);
}
class _View_DishDetailPage2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import45.Wrapper_Item;
  _ItemContent_0_5:import45.Wrapper_ItemContent;
  _query_Label_0_0:import20.QueryList<any>;
  _query_Button_0_1:import20.QueryList<any>;
  _query_Icon_0_2:import20.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Avatar_2_3:import50.Wrapper_Avatar;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_DishDetailPage2,renderType_DishDetailPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import45.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import45.Wrapper_Item(this.parent.parent.parentInjector.get(import46.Form),this.parent.parent.parentInjector.get(import26.Config),new import27.ElementRef(this._el_0),this.renderer,this.parent.parent.parentInjector.get(import47.ItemReorder,(null as any)));
    this._ItemContent_0_5 = new import45.Wrapper_ItemContent();
    this._query_Label_0_0 = new import20.QueryList<any>();
    this._query_Button_0_1 = new import20.QueryList<any>();
    this._query_Icon_0_2 = new import20.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'item-left','');
    this._Avatar_2_3 = new import50.Wrapper_Avatar();
    this._text_3 = this.renderer.createText(this._el_2,'\n          ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'img',(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._text_6,
        this._el_7,
        this._text_9
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'srcChange',this.eventHandler(this._handle_srcChange_4_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import51.Avatar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Avatar_2_3.context; }
    if (((token === import48.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Item_0_4.context; }
    if (((token === import48.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Avatar_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this.parent.parent.context.seller.avatar;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_4,'src',this.viewUtils.sanitizer.sanitize(import49.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(2,'',this.parent.parent.context.seller.firstName,' ',this.parent.parent.context.seller.lastName,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_8,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_srcChange_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.parent.context.seller.avatar = $event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_DishDetailPage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_DishDetailPage2(viewUtils,parentInjector,declarationEl);
}