/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './login';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../providers/auth-data';
import * as import10 from '@angular/forms/src/form_builder';
import * as import11 from 'ionic-angular/components/alert/alert';
import * as import12 from 'ionic-angular/components/loading/loading';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import16 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import17 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import19 from '@angular/core/src/linker/query_list';
import * as import20 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import21 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import23 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import26 from 'ionic-angular/config/config';
import * as import27 from '@angular/core/src/linker/element_ref';
import * as import28 from 'ionic-angular/components/app/app';
import * as import29 from 'ionic-angular/util/keyboard';
import * as import30 from '@angular/core/src/zone/ng_zone';
import * as import31 from 'ionic-angular/navigation/view-controller';
import * as import32 from 'ionic-angular/components/tabs/tabs';
import * as import33 from 'ionic-angular/util/form';
import * as import34 from 'ionic-angular/components/item/item-reorder';
import * as import35 from 'ionic-angular/platform/platform';
import * as import36 from '@angular/core/src/linker/template_ref';
import * as import37 from 'ionic-angular/components/label/label';
import * as import38 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import39 from '@angular/forms/src/directives/ng_control';
import * as import40 from '@angular/forms/src/directives/ng_control_status';
import * as import41 from 'ionic-angular/components/input/input';
import * as import42 from 'ionic-angular/components/item/item';
import * as import43 from '@angular/common/src/directives/ng_if';
import * as import44 from 'ionic-angular/components/button/button';
import * as import45 from 'ionic-angular/components/icon/icon';
import * as import46 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import47 from '@angular/forms/src/directives/control_container';
import * as import48 from 'ionic-angular/components/content/content';
export class Wrapper_LoginPage {
  context:import0.LoginPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this.changed = false;
    this.context = new import0.LoginPage(p0,p1,p2,p3,p4);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_LoginPage_Host:import2.RenderComponentType = (null as any);
class _View_LoginPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _LoginPage_0_4:Wrapper_LoginPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage_Host0,renderType_LoginPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-login',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LoginPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LoginPage_0_4 = new Wrapper_LoginPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.AuthData),this.parentInjector.get(import10.FormBuilder),this.parentInjector.get(import11.AlertController),this.parentInjector.get(import12.LoadingController));
    this._appEl_0.initComponent(this._LoginPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._LoginPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.LoginPage) && (0 === requestNodeIndex))) { return this._LoginPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LoginPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_LoginPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_LoginPage_Host === (null as any))) { (renderType_LoginPage_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_LoginPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoginPageNgFactory:import14.ComponentFactory<import0.LoginPage> = new import14.ComponentFactory<import0.LoginPage>('page-login',viewFactory_LoginPage_Host0,import0.LoginPage);
const styles_LoginPage:any[] = ([] as any[]);
var renderType_LoginPage:import2.RenderComponentType = (null as any);
class _View_LoginPage0 extends import1.AppView<import0.LoginPage> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import3.AppElement;
  _Content_1_4:import15.Wrapper_Content;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _FormGroupDirective_5_3:import16.Wrapper_FormGroupDirective;
  _ControlContainer_5_4:any;
  _NgControlStatusGroup_5_5:import17.Wrapper_NgControlStatusGroup;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import3.AppElement;
  _Item_7_4:import18.Wrapper_Item;
  _ItemContent_7_5:import18.Wrapper_ItemContent;
  _query_Label_7_0:import19.QueryList<any>;
  _query_Button_7_1:import19.QueryList<any>;
  _query_Icon_7_2:import19.QueryList<any>;
  _text_8:any;
  _el_9:any;
  _Label_9_3:import20.Wrapper_Label;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import3.AppElement;
  _FormControlName_12_4:import21.Wrapper_FormControlName;
  _NgControl_12_5:any;
  _NgControlStatus_12_6:import17.Wrapper_NgControlStatus;
  _TextInput_12_7:import22.Wrapper_TextInput;
  _text_13:any;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _appEl_15:import3.AppElement;
  _TemplateRef_15_5:any;
  _NgIf_15_6:import23.Wrapper_NgIf;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import3.AppElement;
  _Item_17_4:import18.Wrapper_Item;
  _ItemContent_17_5:import18.Wrapper_ItemContent;
  _query_Label_17_0:import19.QueryList<any>;
  _query_Button_17_1:import19.QueryList<any>;
  _query_Icon_17_2:import19.QueryList<any>;
  _text_18:any;
  _el_19:any;
  _Label_19_3:import20.Wrapper_Label;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  /*private*/ _appEl_22:import3.AppElement;
  _FormControlName_22_4:import21.Wrapper_FormControlName;
  _NgControl_22_5:any;
  _NgControlStatus_22_6:import17.Wrapper_NgControlStatus;
  _TextInput_22_7:import22.Wrapper_TextInput;
  _text_23:any;
  _text_24:any;
  _anchor_25:any;
  /*private*/ _appEl_25:import3.AppElement;
  _TemplateRef_25_5:any;
  _NgIf_25_6:import23.Wrapper_NgIf;
  _text_26:any;
  _el_27:any;
  /*private*/ _appEl_27:import3.AppElement;
  _Button_27_4:import24.Wrapper_Button;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import3.AppElement;
  _Button_30_4:import24.Wrapper_Button;
  _text_31:any;
  _el_32:any;
  _Icon_32_3:import25.Wrapper_Icon;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  /*private*/ _appEl_35:import3.AppElement;
  _Button_35_4:import24.Wrapper_Button;
  _text_36:any;
  _el_37:any;
  _Icon_37_3:import25.Wrapper_Icon;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  /*private*/ _appEl_41:import3.AppElement;
  _Button_41_4:import24.Wrapper_Button;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  /*private*/ _appEl_44:import3.AppElement;
  _Button_44_4:import24.Wrapper_Button;
  _text_45:any;
  _text_46:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_45:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage0,renderType_LoginPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_1,'padding','');
    this._appEl_1 = new import3.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import15.viewFactory_Content0(this.viewUtils,this.injector(1),this._appEl_1);
    this._Content_1_4 = new import15.Wrapper_Content(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import28.App),this.parentInjector.get(import29.Keyboard),this.parentInjector.get(import30.NgZone),this.parentInjector.get(import31.ViewController,(null as any)),this.parentInjector.get(import32.Tabs,(null as any)));
    this._appEl_1.initComponent(this._Content_1_4.context,([] as any[]),compView_1);
    this._text_2 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_3 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_3,'src','http://www.eate.fr/img/eate_logo.png');
    this._text_4 = this.renderer.createText((null as any),'\n\n	',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'form',(null as any));
    this.renderer.setElementAttribute(this._el_5,'novalidate','');
    this._FormGroupDirective_5_3 = new import16.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_5_4 = this._FormGroupDirective_5_3.context;
    this._NgControlStatusGroup_5_5 = new import17.Wrapper_NgControlStatusGroup(this._ControlContainer_5_4);
    this._text_6 = this.renderer.createText(this._el_5,'\n\n		',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','item item-block');
    this._appEl_7 = new import3.AppElement(7,5,this,this._el_7);
    var compView_7:any = import18.viewFactory_Item0(this.viewUtils,this.injector(7),this._appEl_7);
    this._Item_7_4 = new import18.Wrapper_Item(this.parentInjector.get(import33.Form),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_7),this.renderer,this.parentInjector.get(import34.ItemReorder,(null as any)));
    this._ItemContent_7_5 = new import18.Wrapper_ItemContent();
    this._query_Label_7_0 = new import19.QueryList<any>();
    this._query_Button_7_1 = new import19.QueryList<any>();
    this._query_Icon_7_2 = new import19.QueryList<any>();
    this._appEl_7.initComponent(this._Item_7_4.context,([] as any[]),compView_7);
    this._text_8 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_9,'stacked','');
    this._Label_9_3 = new import20.Wrapper_Label(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_9),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'Email',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_12,'formControlName','email');
    this.renderer.setElementAttribute(this._el_12,'placeholder','Votre email');
    this.renderer.setElementAttribute(this._el_12,'type','email');
    this._appEl_12 = new import3.AppElement(12,7,this,this._el_12);
    var compView_12:any = import22.viewFactory_TextInput0(this.viewUtils,this.injector(12),this._appEl_12);
    this._FormControlName_12_4 = new import21.Wrapper_FormControlName(this._ControlContainer_5_4,(null as any),(null as any),(null as any));
    this._NgControl_12_5 = this._FormControlName_12_4.context;
    this._NgControlStatus_12_6 = new import17.Wrapper_NgControlStatus(this._NgControl_12_5);
    this._TextInput_12_7 = new import22.Wrapper_TextInput(this.parentInjector.get(import26.Config),this.parentInjector.get(import33.Form),this._Item_7_4.context,this.parentInjector.get(import28.App),this.parentInjector.get(import35.Platform),new import27.ElementRef(this._el_12),this.renderer,this._Content_1_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_12_5);
    this._appEl_12.initComponent(this._TextInput_12_7.context,([] as any[]),compView_12);
    compView_12.create(this._TextInput_12_7.context,([] as any[]),(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n		',(null as any));
    this._query_Label_7_0.reset([this._Label_9_3.context]);
    this._Item_7_4.context.contentLabel = this._query_Label_7_0.first;
    compView_7.create(this._Item_7_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_9]),
      ([] as any[]).concat([
        this._text_8,
        this._text_11,
        this._text_13
      ]
      ),
      ([] as any[]).concat([this._el_12]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_14 = this.renderer.createText(this._el_5,'\n		',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor(this._el_5,(null as any));
    this._appEl_15 = new import3.AppElement(15,5,this,this._anchor_15);
    this._TemplateRef_15_5 = new import36.TemplateRef_(this._appEl_15,viewFactory_LoginPage1);
    this._NgIf_15_6 = new import23.Wrapper_NgIf(this._appEl_15.vcRef,this._TemplateRef_15_5);
    this._text_16 = this.renderer.createText(this._el_5,'\n\n		',(null as any));
    this._el_17 = this.renderer.createElement(this._el_5,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','item item-block');
    this._appEl_17 = new import3.AppElement(17,5,this,this._el_17);
    var compView_17:any = import18.viewFactory_Item0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Item_17_4 = new import18.Wrapper_Item(this.parentInjector.get(import33.Form),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_17),this.renderer,this.parentInjector.get(import34.ItemReorder,(null as any)));
    this._ItemContent_17_5 = new import18.Wrapper_ItemContent();
    this._query_Label_17_0 = new import19.QueryList<any>();
    this._query_Button_17_1 = new import19.QueryList<any>();
    this._query_Icon_17_2 = new import19.QueryList<any>();
    this._appEl_17.initComponent(this._Item_17_4.context,([] as any[]),compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_19,'stacked','');
    this._Label_19_3 = new import20.Wrapper_Label(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_19),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'Password',(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_22,'formControlName','password');
    this.renderer.setElementAttribute(this._el_22,'placeholder','Votre mot de passe');
    this.renderer.setElementAttribute(this._el_22,'type','password');
    this._appEl_22 = new import3.AppElement(22,17,this,this._el_22);
    var compView_22:any = import22.viewFactory_TextInput0(this.viewUtils,this.injector(22),this._appEl_22);
    this._FormControlName_22_4 = new import21.Wrapper_FormControlName(this._ControlContainer_5_4,(null as any),(null as any),(null as any));
    this._NgControl_22_5 = this._FormControlName_22_4.context;
    this._NgControlStatus_22_6 = new import17.Wrapper_NgControlStatus(this._NgControl_22_5);
    this._TextInput_22_7 = new import22.Wrapper_TextInput(this.parentInjector.get(import26.Config),this.parentInjector.get(import33.Form),this._Item_17_4.context,this.parentInjector.get(import28.App),this.parentInjector.get(import35.Platform),new import27.ElementRef(this._el_22),this.renderer,this._Content_1_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_22_5);
    this._appEl_22.initComponent(this._TextInput_22_7.context,([] as any[]),compView_22);
    compView_22.create(this._TextInput_22_7.context,([] as any[]),(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n		',(null as any));
    this._query_Label_17_0.reset([this._Label_19_3.context]);
    this._Item_17_4.context.contentLabel = this._query_Label_17_0.first;
    compView_17.create(this._Item_17_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_19]),
      ([] as any[]).concat([
        this._text_18,
        this._text_21,
        this._text_23
      ]
      ),
      ([] as any[]).concat([this._el_22]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_24 = this.renderer.createText(this._el_5,'\n		',(null as any));
    this._anchor_25 = this.renderer.createTemplateAnchor(this._el_5,(null as any));
    this._appEl_25 = new import3.AppElement(25,5,this,this._anchor_25);
    this._TemplateRef_25_5 = new import36.TemplateRef_(this._appEl_25,viewFactory_LoginPage2);
    this._NgIf_25_6 = new import23.Wrapper_NgIf(this._appEl_25.vcRef,this._TemplateRef_25_5);
    this._text_26 = this.renderer.createText(this._el_5,'\n\n		',(null as any));
    this._el_27 = this.renderer.createElement(this._el_5,'button',(null as any));
    this.renderer.setElementAttribute(this._el_27,'block','');
    this.renderer.setElementAttribute(this._el_27,'ion-button','');
    this.renderer.setElementAttribute(this._el_27,'type','submit');
    this._appEl_27 = new import3.AppElement(27,5,this,this._el_27);
    var compView_27:any = import24.viewFactory_Button0(this.viewUtils,this.injector(27),this._appEl_27);
    this._Button_27_4 = new import24.Wrapper_Button((null as any),'',this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_27),this.renderer);
    this._appEl_27.initComponent(this._Button_27_4.context,([] as any[]),compView_27);
    this._text_28 = this.renderer.createText((null as any),'\n      Se connecter\n    ',(null as any));
    compView_27.create(this._Button_27_4.context,[([] as any[]).concat([this._text_28])],(null as any));
    this._text_29 = this.renderer.createText(this._el_5,'\n\n		',(null as any));
    this._el_30 = this.renderer.createElement(this._el_5,'button',(null as any));
    this.renderer.setElementAttribute(this._el_30,'block','');
    this.renderer.setElementAttribute(this._el_30,'color','facebook');
    this.renderer.setElementAttribute(this._el_30,'ion-button','');
    this._appEl_30 = new import3.AppElement(30,5,this,this._el_30);
    var compView_30:any = import24.viewFactory_Button0(this.viewUtils,this.injector(30),this._appEl_30);
    this._Button_30_4 = new import24.Wrapper_Button((null as any),'',this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_30),this.renderer);
    this._appEl_30.initComponent(this._Button_30_4.context,([] as any[]),compView_30);
    this._text_31 = this.renderer.createText((null as any),'\n			Se connecter avec \n			',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_32,'name','logo-facebook');
    this.renderer.setElementAttribute(this._el_32,'role','img');
    this._Icon_32_3 = new import25.Wrapper_Icon(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_32),this.renderer);
    this._text_33 = this.renderer.createText((null as any),'\n		',(null as any));
      compView_30.create(this._Button_30_4.context,[([] as any[]).concat([
        this._text_31,
        this._el_32,
        this._text_33
      ]
    )],(null as any));
    this._text_34 = this.renderer.createText(this._el_5,'\n\n		',(null as any));
    this._el_35 = this.renderer.createElement(this._el_5,'button',(null as any));
    this.renderer.setElementAttribute(this._el_35,'block','');
    this.renderer.setElementAttribute(this._el_35,'color','google-plus');
    this.renderer.setElementAttribute(this._el_35,'ion-button','');
    this._appEl_35 = new import3.AppElement(35,5,this,this._el_35);
    var compView_35:any = import24.viewFactory_Button0(this.viewUtils,this.injector(35),this._appEl_35);
    this._Button_35_4 = new import24.Wrapper_Button((null as any),'',this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_35),this.renderer);
    this._appEl_35.initComponent(this._Button_35_4.context,([] as any[]),compView_35);
    this._text_36 = this.renderer.createText((null as any),'\n			Se connecter avec \n			',(null as any));
    this._el_37 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_37,'name','logo-googleplus');
    this.renderer.setElementAttribute(this._el_37,'role','img');
    this._Icon_37_3 = new import25.Wrapper_Icon(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_37),this.renderer);
    this._text_38 = this.renderer.createText((null as any),'\n		',(null as any));
      compView_35.create(this._Button_35_4.context,[([] as any[]).concat([
        this._text_36,
        this._el_37,
        this._text_38
      ]
    )],(null as any));
    this._text_39 = this.renderer.createText(this._el_5,'\n\n	',(null as any));
    this._text_40 = this.renderer.createText((null as any),'\n\n\n	',(null as any));
    this._el_41 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_41,'block','');
    this.renderer.setElementAttribute(this._el_41,'clear','');
    this.renderer.setElementAttribute(this._el_41,'color','light');
    this.renderer.setElementAttribute(this._el_41,'ion-button','');
    this._appEl_41 = new import3.AppElement(41,1,this,this._el_41);
    var compView_41:any = import24.viewFactory_Button0(this.viewUtils,this.injector(41),this._appEl_41);
    this._Button_41_4 = new import24.Wrapper_Button((null as any),'',this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_41),this.renderer);
    this._appEl_41.initComponent(this._Button_41_4.context,([] as any[]),compView_41);
    this._text_42 = this.renderer.createText((null as any),'\n      Je n\'ai pas encore de compte\n    ',(null as any));
    compView_41.create(this._Button_41_4.context,[([] as any[]).concat([this._text_42])],(null as any));
    this._text_43 = this.renderer.createText((null as any),'\n\n	',(null as any));
    this._el_44 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_44,'block','');
    this.renderer.setElementAttribute(this._el_44,'clear','');
    this.renderer.setElementAttribute(this._el_44,'color','light');
    this.renderer.setElementAttribute(this._el_44,'ion-button','');
    this._appEl_44 = new import3.AppElement(44,1,this,this._el_44);
    var compView_44:any = import24.viewFactory_Button0(this.viewUtils,this.injector(44),this._appEl_44);
    this._Button_44_4 = new import24.Wrapper_Button((null as any),'',this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_44),this.renderer);
    this._appEl_44.initComponent(this._Button_44_4.context,([] as any[]),compView_44);
    this._text_45 = this.renderer.createText((null as any),'\n      J\'ai oublié mon mot de passe\n    ',(null as any));
    compView_44.create(this._Button_44_4.context,[([] as any[]).concat([this._text_45])],(null as any));
    this._text_46 = this.renderer.createText((null as any),'\n',(null as any));
    compView_1.create(this._Content_1_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_2,
        this._el_3,
        this._text_4,
        this._el_5,
        this._text_40,
        this._el_41,
        this._text_43,
        this._el_44,
        this._text_46
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'submit',this.eventHandler(this._handle_submit_5_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_5,'reset',this.eventHandler(this._handle_reset_5_1.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_12,'change',this.eventHandler(this._handle_change_12_0.bind(this)));
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_22,'change',this.eventHandler(this._handle_change_22_0.bind(this)));
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_30,'click',this.eventHandler(this._handle_click_30_0.bind(this)));
    this._expr_40 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_35,'click',this.eventHandler(this._handle_click_35_0.bind(this)));
    this._expr_45 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_41,'click',this.eventHandler(this._handle_click_41_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_44,'click',this.eventHandler(this._handle_click_44_0.bind(this)));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._anchor_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.Label) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Label_9_3.context; }
    if (((token === import38.FormControlName) && (12 === requestNodeIndex))) { return this._FormControlName_12_4.context; }
    if (((token === import39.NgControl) && (12 === requestNodeIndex))) { return this._NgControl_12_5; }
    if (((token === import40.NgControlStatus) && (12 === requestNodeIndex))) { return this._NgControlStatus_12_6.context; }
    if (((token === import41.TextInput) && (12 === requestNodeIndex))) { return this._TextInput_12_7.context; }
    if (((token === import42.Item) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Item_7_4.context; }
    if (((token === import42.ItemContent) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._ItemContent_7_5.context; }
    if (((token === import36.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import43.NgIf) && (15 === requestNodeIndex))) { return this._NgIf_15_6.context; }
    if (((token === import37.Label) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Label_19_3.context; }
    if (((token === import38.FormControlName) && (22 === requestNodeIndex))) { return this._FormControlName_22_4.context; }
    if (((token === import39.NgControl) && (22 === requestNodeIndex))) { return this._NgControl_22_5; }
    if (((token === import40.NgControlStatus) && (22 === requestNodeIndex))) { return this._NgControlStatus_22_6.context; }
    if (((token === import41.TextInput) && (22 === requestNodeIndex))) { return this._TextInput_22_7.context; }
    if (((token === import42.Item) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Item_17_4.context; }
    if (((token === import42.ItemContent) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._ItemContent_17_5.context; }
    if (((token === import36.TemplateRef) && (25 === requestNodeIndex))) { return this._TemplateRef_25_5; }
    if (((token === import43.NgIf) && (25 === requestNodeIndex))) { return this._NgIf_25_6.context; }
    if (((token === import44.Button) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Button_27_4.context; }
    if (((token === import45.Icon) && (32 === requestNodeIndex))) { return this._Icon_32_3.context; }
    if (((token === import44.Button) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Button_30_4.context; }
    if (((token === import45.Icon) && (37 === requestNodeIndex))) { return this._Icon_37_3.context; }
    if (((token === import44.Button) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._Button_35_4.context; }
    if (((token === import46.FormGroupDirective) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._FormGroupDirective_5_3.context; }
    if (((token === import47.ControlContainer) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._ControlContainer_5_4; }
    if (((token === import40.NgControlStatusGroup) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._NgControlStatusGroup_5_5.context; }
    if (((token === import44.Button) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Button_41_4.context; }
    if (((token === import44.Button) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Button_44_4.context; }
    if (((token === import48.Content) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._Content_1_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Content_1_4.detectChangesInternal(this,this._el_1,throwOnChange)) { this._appEl_1.componentView.markAsCheckOnce(); }
    const currVal_4:any = this.context.loginForm;
    this._FormGroupDirective_5_3.check_form(currVal_4,throwOnChange,false);
    this._FormGroupDirective_5_3.detectChangesInternal(this,this._el_5,throwOnChange);
    this._NgControlStatusGroup_5_5.detectChangesInternal(this,this._el_5,throwOnChange);
    if (this._Item_7_4.detectChangesInternal(this,this._el_7,throwOnChange)) { this._appEl_7.componentView.markAsCheckOnce(); }
    this._ItemContent_7_5.detectChangesInternal(this,this._el_7,throwOnChange);
    this._Label_9_3.detectChangesInternal(this,this._el_9,throwOnChange);
    const currVal_13:any = 'email';
    this._FormControlName_12_4.check_name(currVal_13,throwOnChange,false);
    this._FormControlName_12_4.detectChangesInternal(this,this._el_12,throwOnChange);
    this._NgControlStatus_12_6.detectChangesInternal(this,this._el_12,throwOnChange);
    const currVal_20:any = 'Votre email';
    this._TextInput_12_7.check_placeholder(currVal_20,throwOnChange,false);
    const currVal_21:any = 'email';
    this._TextInput_12_7.check_type(currVal_21,throwOnChange,false);
    this._TextInput_12_7.detectChangesInternal(this,this._el_12,throwOnChange);
    const currVal_22:boolean = (!this.context.loginForm.controls.email.valid && (this.context.emailChanged || this.context.submitAttempt));
    this._NgIf_15_6.check_ngIf(currVal_22,throwOnChange,false);
    this._NgIf_15_6.detectChangesInternal(this,this._anchor_15,throwOnChange);
    if (this._Item_17_4.detectChangesInternal(this,this._el_17,throwOnChange)) { this._appEl_17.componentView.markAsCheckOnce(); }
    this._ItemContent_17_5.detectChangesInternal(this,this._el_17,throwOnChange);
    this._Label_19_3.detectChangesInternal(this,this._el_19,throwOnChange);
    const currVal_25:any = 'password';
    this._FormControlName_22_4.check_name(currVal_25,throwOnChange,false);
    this._FormControlName_22_4.detectChangesInternal(this,this._el_22,throwOnChange);
    this._NgControlStatus_22_6.detectChangesInternal(this,this._el_22,throwOnChange);
    const currVal_32:any = 'Votre mot de passe';
    this._TextInput_22_7.check_placeholder(currVal_32,throwOnChange,false);
    const currVal_33:any = 'password';
    this._TextInput_22_7.check_type(currVal_33,throwOnChange,false);
    this._TextInput_22_7.detectChangesInternal(this,this._el_22,throwOnChange);
    const currVal_34:boolean = (!this.context.loginForm.controls.password.valid && (this.context.passwordChanged || this.context.submitAttempt));
    this._NgIf_25_6.check_ngIf(currVal_34,throwOnChange,false);
    this._NgIf_25_6.detectChangesInternal(this,this._anchor_25,throwOnChange);
    const currVal_35:any = '';
    this._Button_27_4.check_block(currVal_35,throwOnChange,false);
    if (this._Button_27_4.detectChangesInternal(this,this._el_27,throwOnChange)) { this._appEl_27.componentView.markAsCheckOnce(); }
    const currVal_37:any = '';
    this._Button_30_4.check_block(currVal_37,throwOnChange,false);
    const currVal_38:any = 'facebook';
    this._Button_30_4.check_color(currVal_38,throwOnChange,false);
    if (this._Button_30_4.detectChangesInternal(this,this._el_30,throwOnChange)) { this._appEl_30.componentView.markAsCheckOnce(); }
    const currVal_39:any = 'logo-facebook';
    this._Icon_32_3.check_name(currVal_39,throwOnChange,false);
    this._Icon_32_3.detectChangesInternal(this,this._el_32,throwOnChange);
    const currVal_42:any = '';
    this._Button_35_4.check_block(currVal_42,throwOnChange,false);
    const currVal_43:any = 'google-plus';
    this._Button_35_4.check_color(currVal_43,throwOnChange,false);
    if (this._Button_35_4.detectChangesInternal(this,this._el_35,throwOnChange)) { this._appEl_35.componentView.markAsCheckOnce(); }
    const currVal_44:any = 'logo-googleplus';
    this._Icon_37_3.check_name(currVal_44,throwOnChange,false);
    this._Icon_37_3.detectChangesInternal(this,this._el_37,throwOnChange);
    const currVal_47:any = '';
    this._Button_41_4.check_clear(currVal_47,throwOnChange,false);
    const currVal_48:any = '';
    this._Button_41_4.check_block(currVal_48,throwOnChange,false);
    const currVal_49:any = 'light';
    this._Button_41_4.check_color(currVal_49,throwOnChange,false);
    if (this._Button_41_4.detectChangesInternal(this,this._el_41,throwOnChange)) { this._appEl_41.componentView.markAsCheckOnce(); }
    const currVal_51:any = '';
    this._Button_44_4.check_clear(currVal_51,throwOnChange,false);
    const currVal_52:any = '';
    this._Button_44_4.check_block(currVal_52,throwOnChange,false);
    const currVal_53:any = 'light';
    this._Button_44_4.check_color(currVal_53,throwOnChange,false);
    if (this._Button_44_4.detectChangesInternal(this,this._el_44,throwOnChange)) { this._appEl_44.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_7_1.dirty) {
        this._query_Button_7_1.reset(([] as any[]));
        this._Item_7_4.context._buttons = this._query_Button_7_1;
        this._query_Button_7_1.notifyOnChanges();
      }
      if (this._query_Icon_7_2.dirty) {
        this._query_Icon_7_2.reset(([] as any[]));
        this._Item_7_4.context._icons = this._query_Icon_7_2;
        this._query_Icon_7_2.notifyOnChanges();
      }
      if (this._query_Button_17_1.dirty) {
        this._query_Button_17_1.reset(([] as any[]));
        this._Item_17_4.context._buttons = this._query_Button_17_1;
        this._query_Button_17_1.notifyOnChanges();
      }
      if (this._query_Icon_17_2.dirty) {
        this._query_Icon_17_2.reset(([] as any[]));
        this._Item_17_4.context._icons = this._query_Icon_17_2;
        this._query_Icon_17_2.notifyOnChanges();
      }
      this._TextInput_12_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_7_4.context.ngAfterContentInit(); }
      this._TextInput_22_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_17_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_27_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_30_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_35_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_41_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_44_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Content_1_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_1,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_5:any = this._NgControlStatusGroup_5_5.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_5,'ng-untouched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_5_5.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_5,'ng-touched',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_5_5.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_5,'ng-pristine',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_5_5.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_5,'ng-dirty',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_5_5.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_5,'ng-valid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatusGroup_5_5.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_5,'ng-invalid',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_12:boolean = (!this.context.loginForm.controls.email.valid && (this.context.emailChanged || this.context.submitAttempt));
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_12,'invalid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_14:any = this._NgControlStatus_12_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_12,'ng-untouched',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_12_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_12,'ng-touched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_12_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_12,'ng-pristine',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_12_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_12,'ng-dirty',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_12_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_12,'ng-valid',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_12_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_12,'ng-invalid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_24:boolean = (!this.context.loginForm.controls.password.valid && (this.context.passwordChanged || this.context.submitAttempt));
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_22,'invalid',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_26:any = this._NgControlStatus_22_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_22,'ng-untouched',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_22_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_22,'ng-touched',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_22_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_22,'ng-pristine',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_22_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_22,'ng-dirty',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_22_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_22,'ng-valid',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_22_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_22,'ng-invalid',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_40:any = this._Icon_32_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_32,'hide',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_45:any = this._Icon_37_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementClass(this._el_37,'hide',currVal_45);
      this._expr_45 = currVal_45;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._FormControlName_12_4.context.ngOnDestroy();
    this._TextInput_12_7.context.ngOnDestroy();
    this._FormControlName_22_4.context.ngOnDestroy();
    this._TextInput_22_7.context.ngOnDestroy();
    this._Icon_32_3.context.ngOnDestroy();
    this._Icon_37_3.context.ngOnDestroy();
    this._Content_1_4.context.ngOnDestroy();
  }
  private _handle_submit_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.loginUser()) !== false);
    const pd_1:any = ((<any>this._FormGroupDirective_5_3.context.onSubmit($event)) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_reset_5_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_5_3.context.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_change_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.elementChanged(this._TextInput_12_7.context)) !== false);
    return (true && pd_0);
  }
  private _handle_change_22_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.elementChanged(this._TextInput_22_7.context)) !== false);
    return (true && pd_0);
  }
  private _handle_click_30_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.facebookLogin()) !== false);
    return (true && pd_0);
  }
  private _handle_click_35_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.googleLogin()) !== false);
    return (true && pd_0);
  }
  private _handle_click_41_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.goToSignup()) !== false);
    return (true && pd_0);
  }
  private _handle_click_44_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.goToResetPassword()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_LoginPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.LoginPage> {
  if ((renderType_LoginPage === (null as any))) { (renderType_LoginPage = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_LoginPage,{})); }
  return new _View_LoginPage0(viewUtils,parentInjector,declarationEl);
}
class _View_LoginPage1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import18.Wrapper_Item;
  _ItemContent_0_5:import18.Wrapper_ItemContent;
  _query_Label_0_0:import19.QueryList<any>;
  _query_Button_0_1:import19.QueryList<any>;
  _query_Icon_0_2:import19.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage1,renderType_LoginPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','error-message item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import18.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import18.Wrapper_Item(this.parent.parentInjector.get(import33.Form),this.parent.parentInjector.get(import26.Config),new import27.ElementRef(this._el_0),this.renderer,this.parent.parentInjector.get(import34.ItemReorder,(null as any)));
    this._ItemContent_0_5 = new import18.Wrapper_ItemContent();
    this._query_Label_0_0 = new import19.QueryList<any>();
    this._query_Button_0_1 = new import19.QueryList<any>();
    this._query_Icon_0_2 = new import19.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'L\'adresse n\'a pas un format correct.',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n		',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_4
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import42.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._Item_0_4.context; }
    if (((token === import42.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_LoginPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_LoginPage1(viewUtils,parentInjector,declarationEl);
}
class _View_LoginPage2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import18.Wrapper_Item;
  _ItemContent_0_5:import18.Wrapper_ItemContent;
  _query_Label_0_0:import19.QueryList<any>;
  _query_Button_0_1:import19.QueryList<any>;
  _query_Icon_0_2:import19.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage2,renderType_LoginPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','error-message item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import18.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import18.Wrapper_Item(this.parent.parentInjector.get(import33.Form),this.parent.parentInjector.get(import26.Config),new import27.ElementRef(this._el_0),this.renderer,this.parent.parentInjector.get(import34.ItemReorder,(null as any)));
    this._ItemContent_0_5 = new import18.Wrapper_ItemContent();
    this._query_Label_0_0 = new import19.QueryList<any>();
    this._query_Button_0_1 = new import19.QueryList<any>();
    this._query_Icon_0_2 = new import19.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Votre mot de passe doit contenir au moins 6 caractères.',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n		',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_4
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import42.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._Item_0_4.context; }
    if (((token === import42.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_LoginPage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_LoginPage2(viewUtils,parentInjector,declarationEl);
}