/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './reset-password';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../providers/auth-data';
import * as import9 from '@angular/forms/src/form_builder';
import * as import10 from 'ionic-angular/navigation/nav-controller';
import * as import11 from 'ionic-angular/components/loading/loading';
import * as import12 from 'ionic-angular/components/alert/alert';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import19 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import20 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import22 from '@angular/core/src/linker/query_list';
import * as import23 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import24 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import26 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import27 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import28 from 'ionic-angular/config/config';
import * as import29 from '@angular/core/src/linker/element_ref';
import * as import30 from 'ionic-angular/navigation/view-controller';
import * as import31 from 'ionic-angular/components/app/app';
import * as import32 from 'ionic-angular/components/toolbar/toolbar';
import * as import33 from 'ionic-angular/util/keyboard';
import * as import34 from '@angular/core/src/zone/ng_zone';
import * as import35 from 'ionic-angular/components/tabs/tabs';
import * as import36 from 'ionic-angular/util/form';
import * as import37 from 'ionic-angular/components/item/item-reorder';
import * as import38 from 'ionic-angular/platform/platform';
import * as import39 from '@angular/core/src/linker/template_ref';
import * as import40 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import41 from 'ionic-angular/components/navbar/navbar';
import * as import42 from 'ionic-angular/components/label/label';
import * as import43 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import44 from '@angular/forms/src/directives/ng_control';
import * as import45 from '@angular/forms/src/directives/ng_control_status';
import * as import46 from 'ionic-angular/components/input/input';
import * as import47 from 'ionic-angular/components/item/item';
import * as import48 from '@angular/common/src/directives/ng_if';
import * as import49 from 'ionic-angular/components/button/button';
import * as import50 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import51 from '@angular/forms/src/directives/control_container';
import * as import52 from 'ionic-angular/components/content/content';
export class Wrapper_ResetPasswordPage {
  context:import0.ResetPasswordPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this.changed = false;
    this.context = new import0.ResetPasswordPage(p0,p1,p2,p3,p4);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_ResetPasswordPage_Host:import2.RenderComponentType = (null as any);
class _View_ResetPasswordPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ResetPasswordPage_0_4:Wrapper_ResetPasswordPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ResetPasswordPage_Host0,renderType_ResetPasswordPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-reset-password',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ResetPasswordPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ResetPasswordPage_0_4 = new Wrapper_ResetPasswordPage(this.parentInjector.get(import8.AuthData),this.parentInjector.get(import9.FormBuilder),this.parentInjector.get(import10.NavController),this.parentInjector.get(import11.LoadingController),this.parentInjector.get(import12.AlertController));
    this._appEl_0.initComponent(this._ResetPasswordPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ResetPasswordPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ResetPasswordPage) && (0 === requestNodeIndex))) { return this._ResetPasswordPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ResetPasswordPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ResetPasswordPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ResetPasswordPage_Host === (null as any))) { (renderType_ResetPasswordPage_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ResetPasswordPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const ResetPasswordPageNgFactory:import14.ComponentFactory<import0.ResetPasswordPage> = new import14.ComponentFactory<import0.ResetPasswordPage>('page-reset-password',viewFactory_ResetPasswordPage_Host0,import0.ResetPasswordPage);
const styles_ResetPasswordPage:any[] = ([] as any[]);
var renderType_ResetPasswordPage:import2.RenderComponentType = (null as any);
class _View_ResetPasswordPage0 extends import1.AppView<import0.ResetPasswordPage> {
  _el_0:any;
  _Header_0_3:import15.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import16.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import17.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Content_9_4:import18.Wrapper_Content;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _FormGroupDirective_13_3:import19.Wrapper_FormGroupDirective;
  _ControlContainer_13_4:any;
  _NgControlStatusGroup_13_5:import20.Wrapper_NgControlStatusGroup;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import3.AppElement;
  _Item_15_4:import21.Wrapper_Item;
  _ItemContent_15_5:import21.Wrapper_ItemContent;
  _query_Label_15_0:import22.QueryList<any>;
  _query_Button_15_1:import22.QueryList<any>;
  _query_Icon_15_2:import22.QueryList<any>;
  _text_16:any;
  _el_17:any;
  _Label_17_3:import23.Wrapper_Label;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import3.AppElement;
  _FormControlName_20_4:import24.Wrapper_FormControlName;
  _NgControl_20_5:any;
  _NgControlStatus_20_6:import20.Wrapper_NgControlStatus;
  _TextInput_20_7:import25.Wrapper_TextInput;
  _text_21:any;
  _text_22:any;
  _anchor_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _TemplateRef_23_5:any;
  _NgIf_23_6:import26.Wrapper_NgIf;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import3.AppElement;
  _Button_25_4:import27.Wrapper_Button;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ResetPasswordPage0,renderType_ResetPasswordPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import15.Wrapper_Header(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import30.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','primary');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import16.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import16.Wrapper_Navbar(this.parentInjector.get(import31.App),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import10.NavController,(null as any)),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import17.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import17.Wrapper_ToolbarTitle(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import32.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      Reset your Password\n    ',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'padding','');
    this._appEl_9 = new import3.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import18.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import18.Wrapper_Content(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import31.App),this.parentInjector.get(import33.Keyboard),this.parentInjector.get(import34.NgZone),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import35.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_11,'src','http://placehold.it/300x100');
    this._text_12 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'form',(null as any));
    this.renderer.setElementAttribute(this._el_13,'novalidate','');
    this._FormGroupDirective_13_3 = new import19.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_13_4 = this._FormGroupDirective_13_3.context;
    this._NgControlStatusGroup_13_5 = new import20.Wrapper_NgControlStatusGroup(this._ControlContainer_13_4);
    this._text_14 = this.renderer.createText(this._el_13,'\n\n    ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','item item-block');
    this._appEl_15 = new import3.AppElement(15,13,this,this._el_15);
    var compView_15:any = import21.viewFactory_Item0(this.viewUtils,this.injector(15),this._appEl_15);
    this._Item_15_4 = new import21.Wrapper_Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_15),this.renderer,this.parentInjector.get(import37.ItemReorder,(null as any)));
    this._ItemContent_15_5 = new import21.Wrapper_ItemContent();
    this._query_Label_15_0 = new import22.QueryList<any>();
    this._query_Button_15_1 = new import22.QueryList<any>();
    this._query_Icon_15_2 = new import22.QueryList<any>();
    this._appEl_15.initComponent(this._Item_15_4.context,([] as any[]),compView_15);
    this._text_16 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_17,'stacked','');
    this._Label_17_3 = new import23.Wrapper_Label(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_17),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Email',(null as any));
    this._text_19 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_20 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_20,'formControlName','email');
    this.renderer.setElementAttribute(this._el_20,'placeholder','Your email address');
    this.renderer.setElementAttribute(this._el_20,'type','email');
    this._appEl_20 = new import3.AppElement(20,15,this,this._el_20);
    var compView_20:any = import25.viewFactory_TextInput0(this.viewUtils,this.injector(20),this._appEl_20);
    this._FormControlName_20_4 = new import24.Wrapper_FormControlName(this._ControlContainer_13_4,(null as any),(null as any),(null as any));
    this._NgControl_20_5 = this._FormControlName_20_4.context;
    this._NgControlStatus_20_6 = new import20.Wrapper_NgControlStatus(this._NgControl_20_5);
    this._TextInput_20_7 = new import25.Wrapper_TextInput(this.parentInjector.get(import28.Config),this.parentInjector.get(import36.Form),this._Item_15_4.context,this.parentInjector.get(import31.App),this.parentInjector.get(import38.Platform),new import29.ElementRef(this._el_20),this.renderer,this._Content_9_4.context,this.parentInjector.get(import10.NavController,(null as any)),this._NgControl_20_5);
    this._appEl_20.initComponent(this._TextInput_20_7.context,([] as any[]),compView_20);
    compView_20.create(this._TextInput_20_7.context,([] as any[]),(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_15_0.reset([this._Label_17_3.context]);
    this._Item_15_4.context.contentLabel = this._query_Label_15_0.first;
    compView_15.create(this._Item_15_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_17]),
      ([] as any[]).concat([
        this._text_16,
        this._text_19,
        this._text_21
      ]
      ),
      ([] as any[]).concat([this._el_20]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_22 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._anchor_23 = this.renderer.createTemplateAnchor(this._el_13,(null as any));
    this._appEl_23 = new import3.AppElement(23,13,this,this._anchor_23);
    this._TemplateRef_23_5 = new import39.TemplateRef_(this._appEl_23,viewFactory_ResetPasswordPage1);
    this._NgIf_23_6 = new import26.Wrapper_NgIf(this._appEl_23.vcRef,this._TemplateRef_23_5);
    this._text_24 = this.renderer.createText(this._el_13,'\n\n    ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_13,'button',(null as any));
    this.renderer.setElementAttribute(this._el_25,'block','');
    this.renderer.setElementAttribute(this._el_25,'ion-button','');
    this.renderer.setElementAttribute(this._el_25,'type','submit');
    this._appEl_25 = new import3.AppElement(25,13,this,this._el_25);
    var compView_25:any = import27.viewFactory_Button0(this.viewUtils,this.injector(25),this._appEl_25);
    this._Button_25_4 = new import27.Wrapper_Button((null as any),'',this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_25),this.renderer);
    this._appEl_25.initComponent(this._Button_25_4.context,([] as any[]),compView_25);
    this._text_26 = this.renderer.createText((null as any),'\n      Reset your Password\n    ',(null as any));
    compView_25.create(this._Button_25_4.context,[([] as any[]).concat([this._text_26])],(null as any));
    this._text_27 = this.renderer.createText(this._el_13,'\n  ',(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n',(null as any));
    compView_9.create(this._Content_9_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_12,
        this._el_13,
        this._text_28
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_29 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_13,'submit',this.eventHandler(this._handle_submit_13_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_13,'reset',this.eventHandler(this._handle_reset_13_1.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_20,'change',this.eventHandler(this._handle_change_20_0.bind(this)));
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._anchor_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import40.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import41.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4.context; }
    if (((token === import32.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3.context; }
    if (((token === import42.Label) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Label_17_3.context; }
    if (((token === import43.FormControlName) && (20 === requestNodeIndex))) { return this._FormControlName_20_4.context; }
    if (((token === import44.NgControl) && (20 === requestNodeIndex))) { return this._NgControl_20_5; }
    if (((token === import45.NgControlStatus) && (20 === requestNodeIndex))) { return this._NgControlStatus_20_6.context; }
    if (((token === import46.TextInput) && (20 === requestNodeIndex))) { return this._TextInput_20_7.context; }
    if (((token === import47.Item) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Item_15_4.context; }
    if (((token === import47.ItemContent) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._ItemContent_15_5.context; }
    if (((token === import39.TemplateRef) && (23 === requestNodeIndex))) { return this._TemplateRef_23_5; }
    if (((token === import48.NgIf) && (23 === requestNodeIndex))) { return this._NgIf_23_6.context; }
    if (((token === import49.Button) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Button_25_4.context; }
    if (((token === import50.FormGroupDirective) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._FormGroupDirective_13_3.context; }
    if (((token === import51.ControlContainer) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._ControlContainer_13_4; }
    if (((token === import45.NgControlStatusGroup) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._NgControlStatusGroup_13_5.context; }
    if (((token === import52.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Content_9_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_0:any = 'primary';
    this._Navbar_2_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._Content_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    const currVal_7:any = this.context.resetPasswordForm;
    this._FormGroupDirective_13_3.check_form(currVal_7,throwOnChange,false);
    this._FormGroupDirective_13_3.detectChangesInternal(this,this._el_13,throwOnChange);
    this._NgControlStatusGroup_13_5.detectChangesInternal(this,this._el_13,throwOnChange);
    if (this._Item_15_4.detectChangesInternal(this,this._el_15,throwOnChange)) { this._appEl_15.componentView.markAsCheckOnce(); }
    this._ItemContent_15_5.detectChangesInternal(this,this._el_15,throwOnChange);
    this._Label_17_3.detectChangesInternal(this,this._el_17,throwOnChange);
    const currVal_16:any = 'email';
    this._FormControlName_20_4.check_name(currVal_16,throwOnChange,false);
    this._FormControlName_20_4.detectChangesInternal(this,this._el_20,throwOnChange);
    this._NgControlStatus_20_6.detectChangesInternal(this,this._el_20,throwOnChange);
    const currVal_23:any = 'Your email address';
    this._TextInput_20_7.check_placeholder(currVal_23,throwOnChange,false);
    const currVal_24:any = 'email';
    this._TextInput_20_7.check_type(currVal_24,throwOnChange,false);
    this._TextInput_20_7.detectChangesInternal(this,this._el_20,throwOnChange);
    const currVal_25:boolean = (!this.context.resetPasswordForm.controls.email.valid && (this.context.emailChanged || this.context.submitAttempt));
    this._NgIf_23_6.check_ngIf(currVal_25,throwOnChange,false);
    this._NgIf_23_6.detectChangesInternal(this,this._anchor_23,throwOnChange);
    const currVal_26:any = '';
    this._Button_25_4.check_block(currVal_26,throwOnChange,false);
    if (this._Button_25_4.detectChangesInternal(this,this._el_25,throwOnChange)) { this._appEl_25.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_15_1.dirty) {
        this._query_Button_15_1.reset(([] as any[]));
        this._Item_15_4.context._buttons = this._query_Button_15_1;
        this._query_Button_15_1.notifyOnChanges();
      }
      if (this._query_Icon_15_2.dirty) {
        this._query_Icon_15_2.reset(([] as any[]));
        this._Item_15_4.context._icons = this._query_Icon_15_2;
        this._query_Icon_15_2.notifyOnChanges();
      }
      this._TextInput_20_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_15_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_25_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_9_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_8:any = this._NgControlStatusGroup_13_5.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_13,'ng-untouched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_13_5.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_13,'ng-touched',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatusGroup_13_5.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_13,'ng-pristine',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatusGroup_13_5.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_13,'ng-dirty',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatusGroup_13_5.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_13,'ng-valid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatusGroup_13_5.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_13,'ng-invalid',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_15:boolean = (!this.context.resetPasswordForm.controls.email.valid && (this.context.emailChanged || this.context.submitAttempt));
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_20,'invalid',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_17:any = this._NgControlStatus_20_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_20,'ng-untouched',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_20_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_20,'ng-touched',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_20_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_20,'ng-pristine',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_20_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_20,'ng-dirty',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_20_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_20,'ng-valid',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_20_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_20,'ng-invalid',currVal_22);
      this._expr_22 = currVal_22;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._FormControlName_20_4.context.ngOnDestroy();
    this._TextInput_20_7.context.ngOnDestroy();
    this._Content_9_4.context.ngOnDestroy();
  }
  private _handle_submit_13_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.resetPassword()) !== false);
    const pd_1:any = ((<any>this._FormGroupDirective_13_3.context.onSubmit($event)) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_reset_13_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_13_3.context.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_change_20_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.elementChanged(this._TextInput_20_7.context)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ResetPasswordPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ResetPasswordPage> {
  if ((renderType_ResetPasswordPage === (null as any))) { (renderType_ResetPasswordPage = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_ResetPasswordPage,{})); }
  return new _View_ResetPasswordPage0(viewUtils,parentInjector,declarationEl);
}
class _View_ResetPasswordPage1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import21.Wrapper_Item;
  _ItemContent_0_5:import21.Wrapper_ItemContent;
  _query_Label_0_0:import22.QueryList<any>;
  _query_Button_0_1:import22.QueryList<any>;
  _query_Icon_0_2:import22.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ResetPasswordPage1,renderType_ResetPasswordPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','error-message item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import21.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import21.Wrapper_Item(this.parent.parentInjector.get(import36.Form),this.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_0),this.renderer,this.parent.parentInjector.get(import37.ItemReorder,(null as any)));
    this._ItemContent_0_5 = new import21.Wrapper_ItemContent();
    this._query_Label_0_0 = new import22.QueryList<any>();
    this._query_Button_0_1 = new import22.QueryList<any>();
    this._query_Icon_0_2 = new import22.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Please enter a valid email.',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_4
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import47.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._Item_0_4.context; }
    if (((token === import47.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ResetPasswordPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ResetPasswordPage1(viewUtils,parentInjector,declarationEl);
}