/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './event-detail';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from '../../providers/event-data';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import21 from '@angular/core/src/linker/query_list';
import * as import22 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import23 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import24 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import26 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import27 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import28 from 'ionic-angular/config/config';
import * as import29 from '@angular/core/src/linker/element_ref';
import * as import30 from 'ionic-angular/navigation/view-controller';
import * as import31 from 'ionic-angular/components/app/app';
import * as import32 from 'ionic-angular/components/toolbar/toolbar';
import * as import33 from 'ionic-angular/util/keyboard';
import * as import34 from '@angular/core/src/zone/ng_zone';
import * as import35 from 'ionic-angular/components/tabs/tabs';
import * as import36 from 'ionic-angular/gestures/gesture-controller';
import * as import37 from 'ionic-angular/util/form';
import * as import38 from 'ionic-angular/components/item/item-reorder';
import * as import39 from 'ionic-angular/platform/platform';
import * as import40 from '@angular/core/src/linker/template_ref';
import * as import41 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import42 from 'ionic-angular/components/navbar/navbar';
import * as import43 from 'ionic-angular/components/grid/grid';
import * as import44 from 'ionic-angular/components/card/card';
import * as import45 from 'ionic-angular/components/label/label';
import * as import46 from '@angular/forms/src/directives/ng_model';
import * as import47 from '@angular/forms/src/directives/ng_control';
import * as import48 from '@angular/forms/src/directives/ng_control_status';
import * as import49 from 'ionic-angular/components/input/input';
import * as import50 from 'ionic-angular/components/item/item';
import * as import51 from '@angular/common/src/directives/ng_if';
import * as import52 from 'ionic-angular/components/button/button';
import * as import53 from 'ionic-angular/components/list/list';
import * as import54 from 'ionic-angular/components/content/content';
import * as import55 from '@angular/core/src/security';
export class Wrapper_EventDetailPage {
  context:import0.EventDetailPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.EventDetailPage(p0,p1,p2);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_EventDetailPage_Host:import2.RenderComponentType = (null as any);
class _View_EventDetailPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _EventDetailPage_0_4:Wrapper_EventDetailPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_EventDetailPage_Host0,renderType_EventDetailPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-event-detail',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_EventDetailPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._EventDetailPage_0_4 = new Wrapper_EventDetailPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams),this.parentInjector.get(import10.EventData));
    this._appEl_0.initComponent(this._EventDetailPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._EventDetailPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.EventDetailPage) && (0 === requestNodeIndex))) { return this._EventDetailPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._EventDetailPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_EventDetailPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_EventDetailPage_Host === (null as any))) { (renderType_EventDetailPage_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_EventDetailPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const EventDetailPageNgFactory:import12.ComponentFactory<import0.EventDetailPage> = new import12.ComponentFactory<import0.EventDetailPage>('page-event-detail',viewFactory_EventDetailPage_Host0,import0.EventDetailPage);
const styles_EventDetailPage:any[] = ([] as any[]);
var renderType_EventDetailPage:import2.RenderComponentType = (null as any);
class _View_EventDetailPage0 extends import1.AppView<import0.EventDetailPage> {
  _el_0:any;
  _Header_0_3:import13.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import14.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import15.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  /*private*/ _appEl_8:import3.AppElement;
  _Content_8_4:import16.Wrapper_Content;
  _text_9:any;
  _el_10:any;
  _Row_10_3:import17.Wrapper_Row;
  _text_11:any;
  _el_12:any;
  _Col_12_3:import17.Wrapper_Col;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _Col_15_3:import17.Wrapper_Col;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _Card_19_3:import18.Wrapper_Card;
  _text_20:any;
  _el_21:any;
  _CardHeader_21_3:import18.Wrapper_CardHeader;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _CardContent_24_3:import18.Wrapper_CardContent;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _Card_38_3:import18.Wrapper_Card;
  _text_39:any;
  _el_40:any;
  _CardHeader_40_3:import18.Wrapper_CardHeader;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _CardContent_43_3:import18.Wrapper_CardContent;
  _text_44:any;
  _el_45:any;
  _List_45_3:import19.Wrapper_List;
  _text_46:any;
  _el_47:any;
  /*private*/ _appEl_47:import3.AppElement;
  _Item_47_4:import20.Wrapper_Item;
  _ItemContent_47_5:import20.Wrapper_ItemContent;
  _query_Label_47_0:import21.QueryList<any>;
  _query_Button_47_1:import21.QueryList<any>;
  _query_Icon_47_2:import21.QueryList<any>;
  _text_48:any;
  _el_49:any;
  _Label_49_3:import22.Wrapper_Label;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  /*private*/ _appEl_52:import3.AppElement;
  _NgModel_52_4:import23.Wrapper_NgModel;
  _NgControl_52_5:any;
  _NgControlStatus_52_6:import24.Wrapper_NgControlStatus;
  _TextInput_52_7:import25.Wrapper_TextInput;
  _text_53:any;
  _text_54:any;
  _anchor_55:any;
  /*private*/ _appEl_55:import3.AppElement;
  _TemplateRef_55_5:any;
  _NgIf_55_6:import26.Wrapper_NgIf;
  _text_56:any;
  _anchor_57:any;
  /*private*/ _appEl_57:import3.AppElement;
  _TemplateRef_57_5:any;
  _NgIf_57_6:import26.Wrapper_NgIf;
  _text_58:any;
  _el_59:any;
  /*private*/ _appEl_59:import3.AppElement;
  _Button_59_4:import27.Wrapper_Button;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  /*private*/ _appEl_62:import3.AppElement;
  _Button_62_4:import27.Wrapper_Button;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_EventDetailPage0,renderType_EventDetailPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import13.Wrapper_Header(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import30.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import14.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import14.Wrapper_Navbar(this.parentInjector.get(import31.App),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import15.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import15.Wrapper_ToolbarTitle(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import32.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[])],(null as any));
    this._text_5 = this.renderer.createText((null as any),'\n	',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_5
      ]
      )
    ]
    ,(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_7 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_8 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_8,'padding','');
    this._appEl_8 = new import3.AppElement(8,(null as any),this,this._el_8);
    var compView_8:any = import16.viewFactory_Content0(this.viewUtils,this.injector(8),this._appEl_8);
    this._Content_8_4 = new import16.Wrapper_Content(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_8),this.renderer,this.parentInjector.get(import31.App),this.parentInjector.get(import33.Keyboard),this.parentInjector.get(import34.NgZone),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import35.Tabs,(null as any)));
    this._appEl_8.initComponent(this._Content_8_4.context,([] as any[]),compView_8);
    this._text_9 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_10,'padding','');
    this._Row_10_3 = new import17.Wrapper_Row();
    this._text_11 = this.renderer.createText(this._el_10,'\n		',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_12,'width-80','');
    this._Col_12_3 = new import17.Wrapper_Col();
    this._text_13 = this.renderer.createText(this._el_12,'\n			Current Revenue\n		',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n		',(null as any));
    this._el_15 = this.renderer.createElement(this._el_10,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_15,'width-20','');
    this._Col_15_3 = new import17.Wrapper_Col();
    this._text_16 = this.renderer.createText(this._el_15,'',(null as any));
    this._text_17 = this.renderer.createText(this._el_10,'\n	',(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_19_3 = new import18.Wrapper_Card(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_19),this.renderer);
    this._text_20 = this.renderer.createText(this._el_19,'\n		',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'ion-card-header',(null as any));
    this._CardHeader_21_3 = new import18.Wrapper_CardHeader(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_21),this.renderer);
    this._text_22 = this.renderer.createText(this._el_21,'',(null as any));
    this._text_23 = this.renderer.createText(this._el_19,'\n		',(null as any));
    this._el_24 = this.renderer.createElement(this._el_19,'ion-card-content',(null as any));
    this._CardContent_24_3 = new import18.Wrapper_CardContent(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_24),this.renderer);
    this._text_25 = this.renderer.createText(this._el_24,'\n			',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'p',(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'Ticket: ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'strong',(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'',(null as any));
    this._text_30 = this.renderer.createText(this._el_24,'\n			',(null as any));
    this._el_31 = this.renderer.createElement(this._el_24,'p',(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'Date: ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_31,'strong',(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'',(null as any));
    this._text_35 = this.renderer.createText(this._el_24,'\n		',(null as any));
    this._text_36 = this.renderer.createText(this._el_19,'\n	',(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_38 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','add-guest-form');
    this._Card_38_3 = new import18.Wrapper_Card(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_38),this.renderer);
    this._text_39 = this.renderer.createText(this._el_38,'\n		',(null as any));
    this._el_40 = this.renderer.createElement(this._el_38,'ion-card-header',(null as any));
    this._CardHeader_40_3 = new import18.Wrapper_CardHeader(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_40),this.renderer);
    this._text_41 = this.renderer.createText(this._el_40,'\n			Add Guests\n		',(null as any));
    this._text_42 = this.renderer.createText(this._el_38,'\n		',(null as any));
    this._el_43 = this.renderer.createElement(this._el_38,'ion-card-content',(null as any));
    this._CardContent_43_3 = new import18.Wrapper_CardContent(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_43),this.renderer);
    this._text_44 = this.renderer.createText(this._el_43,'\n			',(null as any));
    this._el_45 = this.renderer.createElement(this._el_43,'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_45,'no-lines','');
    this._List_45_3 = new import19.Wrapper_List(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_45),this.renderer,this.parentInjector.get(import36.GestureController));
    this._text_46 = this.renderer.createText(this._el_45,'\n				',(null as any));
    this._el_47 = this.renderer.createElement(this._el_45,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_47,'class','item item-block');
    this._appEl_47 = new import3.AppElement(47,45,this,this._el_47);
    var compView_47:any = import20.viewFactory_Item0(this.viewUtils,this.injector(47),this._appEl_47);
    this._Item_47_4 = new import20.Wrapper_Item(this.parentInjector.get(import37.Form),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_47),this.renderer,this.parentInjector.get(import38.ItemReorder,(null as any)));
    this._ItemContent_47_5 = new import20.Wrapper_ItemContent();
    this._query_Label_47_0 = new import21.QueryList<any>();
    this._query_Button_47_1 = new import21.QueryList<any>();
    this._query_Icon_47_2 = new import21.QueryList<any>();
    this._appEl_47.initComponent(this._Item_47_4.context,([] as any[]),compView_47);
    this._text_48 = this.renderer.createText((null as any),'\n					',(null as any));
    this._el_49 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_49,'stacked','');
    this._Label_49_3 = new import22.Wrapper_Label(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_49),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_50 = this.renderer.createText(this._el_49,'Name',(null as any));
    this._text_51 = this.renderer.createText((null as any),'\n					',(null as any));
    this._el_52 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_52,'placeholder','What\'s your guest\'s name?');
    this.renderer.setElementAttribute(this._el_52,'type','text');
    this._appEl_52 = new import3.AppElement(52,47,this,this._el_52);
    var compView_52:any = import25.viewFactory_TextInput0(this.viewUtils,this.injector(52),this._appEl_52);
    this._NgModel_52_4 = new import23.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_52_5 = this._NgModel_52_4.context;
    this._NgControlStatus_52_6 = new import24.Wrapper_NgControlStatus(this._NgControl_52_5);
    this._TextInput_52_7 = new import25.Wrapper_TextInput(this.parentInjector.get(import28.Config),this.parentInjector.get(import37.Form),this._Item_47_4.context,this.parentInjector.get(import31.App),this.parentInjector.get(import39.Platform),new import29.ElementRef(this._el_52),this.renderer,this._Content_8_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_52_5);
    this._appEl_52.initComponent(this._TextInput_52_7.context,([] as any[]),compView_52);
    compView_52.create(this._TextInput_52_7.context,([] as any[]),(null as any));
    this._text_53 = this.renderer.createText((null as any),'\n				',(null as any));
    this._query_Label_47_0.reset([this._Label_49_3.context]);
    this._Item_47_4.context.contentLabel = this._query_Label_47_0.first;
    compView_47.create(this._Item_47_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_49]),
      ([] as any[]).concat([
        this._text_48,
        this._text_51,
        this._text_53
      ]
      ),
      ([] as any[]).concat([this._el_52]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_54 = this.renderer.createText(this._el_45,'\n				',(null as any));
    this._anchor_55 = this.renderer.createTemplateAnchor(this._el_45,(null as any));
    this._appEl_55 = new import3.AppElement(55,45,this,this._anchor_55);
    this._TemplateRef_55_5 = new import40.TemplateRef_(this._appEl_55,viewFactory_EventDetailPage1);
    this._NgIf_55_6 = new import26.Wrapper_NgIf(this._appEl_55.vcRef,this._TemplateRef_55_5);
    this._text_56 = this.renderer.createText(this._el_45,'\n				',(null as any));
    this._anchor_57 = this.renderer.createTemplateAnchor(this._el_45,(null as any));
    this._appEl_57 = new import3.AppElement(57,45,this,this._anchor_57);
    this._TemplateRef_57_5 = new import40.TemplateRef_(this._appEl_57,viewFactory_EventDetailPage2);
    this._NgIf_57_6 = new import26.Wrapper_NgIf(this._appEl_57.vcRef,this._TemplateRef_57_5);
    this._text_58 = this.renderer.createText(this._el_45,'\n				',(null as any));
    this._el_59 = this.renderer.createElement(this._el_45,'button',(null as any));
    this.renderer.setElementAttribute(this._el_59,'block','');
    this.renderer.setElementAttribute(this._el_59,'color','primary');
    this.renderer.setElementAttribute(this._el_59,'ion-button','');
    this._appEl_59 = new import3.AppElement(59,45,this,this._el_59);
    var compView_59:any = import27.viewFactory_Button0(this.viewUtils,this.injector(59),this._appEl_59);
    this._Button_59_4 = new import27.Wrapper_Button((null as any),'',this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_59),this.renderer);
    this._appEl_59.initComponent(this._Button_59_4.context,([] as any[]),compView_59);
    this._text_60 = this.renderer.createText((null as any),'\n					Take a Picture\n				',(null as any));
    compView_59.create(this._Button_59_4.context,[([] as any[]).concat([this._text_60])],(null as any));
    this._text_61 = this.renderer.createText(this._el_45,'\n				',(null as any));
    this._el_62 = this.renderer.createElement(this._el_45,'button',(null as any));
    this.renderer.setElementAttribute(this._el_62,'block','');
    this.renderer.setElementAttribute(this._el_62,'color','primary');
    this.renderer.setElementAttribute(this._el_62,'ion-button','');
    this._appEl_62 = new import3.AppElement(62,45,this,this._el_62);
    var compView_62:any = import27.viewFactory_Button0(this.viewUtils,this.injector(62),this._appEl_62);
    this._Button_62_4 = new import27.Wrapper_Button((null as any),'',this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_62),this.renderer);
    this._appEl_62.initComponent(this._Button_62_4.context,([] as any[]),compView_62);
    this._text_63 = this.renderer.createText((null as any),'\n        Add Guest\n      ',(null as any));
    compView_62.create(this._Button_62_4.context,[([] as any[]).concat([this._text_63])],(null as any));
    this._text_64 = this.renderer.createText(this._el_45,'\n			',(null as any));
    this._text_65 = this.renderer.createText(this._el_43,'\n		',(null as any));
    this._text_66 = this.renderer.createText(this._el_38,'\n	',(null as any));
    this._text_67 = this.renderer.createText((null as any),'\n',(null as any));
    compView_8.create(this._Content_8_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_9,
        this._el_10,
        this._text_18,
        this._el_19,
        this._text_37,
        this._el_38,
        this._text_67
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_52,'ngModelChange',this.eventHandler(this._handle_ngModelChange_52_0.bind(this)));
    const subscription_0:any = this._NgModel_52_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_52_0.bind(this)));
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_59,'click',this.eventHandler(this._handle_click_59_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_62,'click',this.eventHandler(this._handle_click_62_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._anchor_55,
      this._text_56,
      this._anchor_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._text_67
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.ToolbarTitle) && (4 === requestNodeIndex))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import42.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Navbar_2_4.context; }
    if (((token === import32.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Header_0_3.context; }
    if (((token === import43.Col) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Col_12_3.context; }
    if (((token === import43.Col) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Col_15_3.context; }
    if (((token === import43.Row) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Row_10_3.context; }
    if (((token === import44.CardHeader) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._CardHeader_21_3.context; }
    if (((token === import44.CardContent) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._CardContent_24_3.context; }
    if (((token === import44.Card) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._Card_19_3.context; }
    if (((token === import44.CardHeader) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._CardHeader_40_3.context; }
    if (((token === import45.Label) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._Label_49_3.context; }
    if (((token === import46.NgModel) && (52 === requestNodeIndex))) { return this._NgModel_52_4.context; }
    if (((token === import47.NgControl) && (52 === requestNodeIndex))) { return this._NgControl_52_5; }
    if (((token === import48.NgControlStatus) && (52 === requestNodeIndex))) { return this._NgControlStatus_52_6.context; }
    if (((token === import49.TextInput) && (52 === requestNodeIndex))) { return this._TextInput_52_7.context; }
    if (((token === import50.Item) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._Item_47_4.context; }
    if (((token === import50.ItemContent) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._ItemContent_47_5.context; }
    if (((token === import40.TemplateRef) && (55 === requestNodeIndex))) { return this._TemplateRef_55_5; }
    if (((token === import51.NgIf) && (55 === requestNodeIndex))) { return this._NgIf_55_6.context; }
    if (((token === import40.TemplateRef) && (57 === requestNodeIndex))) { return this._TemplateRef_57_5; }
    if (((token === import51.NgIf) && (57 === requestNodeIndex))) { return this._NgIf_57_6.context; }
    if (((token === import52.Button) && ((59 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._Button_59_4.context; }
    if (((token === import52.Button) && ((62 <= requestNodeIndex) && (requestNodeIndex <= 63)))) { return this._Button_62_4.context; }
    if (((token === import53.List) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._List_45_3.context; }
    if (((token === import44.CardContent) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._CardContent_43_3.context; }
    if (((token === import44.Card) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._Card_38_3.context; }
    if (((token === import54.Content) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 67)))) { return this._Content_8_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._Content_8_4.detectChangesInternal(this,this._el_8,throwOnChange)) { this._appEl_8.componentView.markAsCheckOnce(); }
    this._Row_10_3.detectChangesInternal(this,this._el_10,throwOnChange);
    this._Col_12_3.detectChangesInternal(this,this._el_12,throwOnChange);
    this._Col_15_3.detectChangesInternal(this,this._el_15,throwOnChange);
    this._Card_19_3.detectChangesInternal(this,this._el_19,throwOnChange);
    this._CardHeader_21_3.detectChangesInternal(this,this._el_21,throwOnChange);
    this._CardContent_24_3.detectChangesInternal(this,this._el_24,throwOnChange);
    this._Card_38_3.detectChangesInternal(this,this._el_38,throwOnChange);
    this._CardHeader_40_3.detectChangesInternal(this,this._el_40,throwOnChange);
    this._CardContent_43_3.detectChangesInternal(this,this._el_43,throwOnChange);
    this._List_45_3.detectChangesInternal(this,this._el_45,throwOnChange);
    if (this._Item_47_4.detectChangesInternal(this,this._el_47,throwOnChange)) { this._appEl_47.componentView.markAsCheckOnce(); }
    this._ItemContent_47_5.detectChangesInternal(this,this._el_47,throwOnChange);
    this._Label_49_3.detectChangesInternal(this,this._el_49,throwOnChange);
    const currVal_10:any = this.context.guestName;
    this._NgModel_52_4.check_model(currVal_10,throwOnChange,false);
    this._NgModel_52_4.detectChangesInternal(this,this._el_52,throwOnChange);
    this._NgControlStatus_52_6.detectChangesInternal(this,this._el_52,throwOnChange);
    const currVal_17:any = 'What\'s your guest\'s name?';
    this._TextInput_52_7.check_placeholder(currVal_17,throwOnChange,false);
    const currVal_18:any = 'text';
    this._TextInput_52_7.check_type(currVal_18,throwOnChange,false);
    this._TextInput_52_7.detectChangesInternal(this,this._el_52,throwOnChange);
    const currVal_19:any = this.context.guestPicture;
    this._NgIf_55_6.check_ngIf(currVal_19,throwOnChange,false);
    this._NgIf_55_6.detectChangesInternal(this,this._anchor_55,throwOnChange);
    const currVal_20:any = this.context.guestPicture;
    this._NgIf_57_6.check_ngIf(currVal_20,throwOnChange,false);
    this._NgIf_57_6.detectChangesInternal(this,this._anchor_57,throwOnChange);
    const currVal_22:any = '';
    this._Button_59_4.check_block(currVal_22,throwOnChange,false);
    const currVal_23:any = 'primary';
    this._Button_59_4.check_color(currVal_23,throwOnChange,false);
    if (this._Button_59_4.detectChangesInternal(this,this._el_59,throwOnChange)) { this._appEl_59.componentView.markAsCheckOnce(); }
    const currVal_25:any = '';
    this._Button_62_4.check_block(currVal_25,throwOnChange,false);
    const currVal_26:any = 'primary';
    this._Button_62_4.check_color(currVal_26,throwOnChange,false);
    if (this._Button_62_4.detectChangesInternal(this,this._el_62,throwOnChange)) { this._appEl_62.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_47_1.dirty) {
        this._query_Button_47_1.reset(([] as any[]));
        this._Item_47_4.context._buttons = this._query_Button_47_1;
        this._query_Button_47_1.notifyOnChanges();
      }
      if (this._query_Icon_47_2.dirty) {
        this._query_Icon_47_2.reset(([] as any[]));
        this._Item_47_4.context._icons = this._query_Icon_47_2;
        this._query_Icon_47_2.notifyOnChanges();
      }
      this._TextInput_52_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_47_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_59_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_62_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_8_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_8,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = (((this.context.currentEvent == (null as any))? (null as any): this.context.currentEvent.revenue) > 0);
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_15,'profitable',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = (((this.context.currentEvent == (null as any))? (null as any): this.context.currentEvent.revenue) < 0);
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_15,'no-profit',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'\n			',((this.context.currentEvent == (null as any))? (null as any): this.context.currentEvent.revenue),'\n		');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_16,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import4.interpolate(1,'\n			',((this.context.currentEvent == (null as any))? (null as any): this.context.currentEvent.name),'\n		');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_22,currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = import4.interpolate(1,'',((this.context.currentEvent == (null as any))? (null as any): this.context.currentEvent.price),'');
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_29,currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = import4.interpolate(1,'',((this.context.currentEvent == (null as any))? (null as any): this.context.currentEvent.date),'');
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_34,currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_11:any = this._NgControlStatus_52_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_52,'ng-untouched',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_52_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_52,'ng-touched',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatus_52_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_52,'ng-pristine',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatus_52_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_52,'ng-dirty',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_52_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_52,'ng-valid',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_52_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_52,'ng-invalid',currVal_16);
      this._expr_16 = currVal_16;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._NgModel_52_4.context.ngOnDestroy();
    this._TextInput_52_7.context.ngOnDestroy();
    this._Content_8_4.context.ngOnDestroy();
  }
  private _handle_ngModelChange_52_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.guestName = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_59_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.takePicture()) !== false);
    return (true && pd_0);
  }
  private _handle_click_62_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.addGuest(this.context.guestName)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_EventDetailPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.EventDetailPage> {
  if ((renderType_EventDetailPage === (null as any))) { (renderType_EventDetailPage = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,styles_EventDetailPage,{})); }
  return new _View_EventDetailPage0(viewUtils,parentInjector,declarationEl);
}
class _View_EventDetailPage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_EventDetailPage1,renderType_EventDetailPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Picture taken!',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_EventDetailPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_EventDetailPage1(viewUtils,parentInjector,declarationEl);
}
class _View_EventDetailPage2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_EventDetailPage2,renderType_EventDetailPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_0,'srcChange',this.eventHandler(this._handle_srcChange_0_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],[disposable_0],([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = ('data:image/jpeg;base64,' + this.parent.context.guestPicture);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import55.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_srcChange_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>('data:image/jpeg;base64,' + (this.parent.context.guestPicture = $event))) !== false);
    return (true && pd_0);
  }
}
function viewFactory_EventDetailPage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_EventDetailPage2(viewUtils,parentInjector,declarationEl);
}