/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './master-page';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../providers/profile-data';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/core/src/linker/query_list';
import * as import12 from '../../node_modules/ionic-angular/components/menu/menu.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import14 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import16 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/nav/nav.ngfactory';
import * as import18 from 'ionic-angular/components/menu/menu-controller';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from 'ionic-angular/config/config';
import * as import21 from 'ionic-angular/platform/platform';
import * as import22 from 'ionic-angular/util/keyboard';
import * as import23 from '@angular/core/src/zone/ng_zone';
import * as import24 from 'ionic-angular/gestures/gesture-controller';
import * as import25 from 'ionic-angular/components/app/app';
import * as import26 from 'ionic-angular/navigation/view-controller';
import * as import27 from 'ionic-angular/components/tabs/tabs';
import * as import28 from '@angular/core/src/linker/template_ref';
import * as import29 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import30 from 'ionic-angular/navigation/nav-controller-base';
import * as import31 from '@angular/core/src/linker/component_factory_resolver';
import * as import32 from 'ionic-angular/transitions/transition-controller';
import * as import33 from 'ionic-angular/navigation/deep-linker';
import * as import34 from '@angular/common/src/directives/ng_if';
import * as import35 from '@angular/common/src/directives/ng_for';
import * as import36 from 'ionic-angular/components/list/list';
import * as import37 from 'ionic-angular/components/content/content';
import * as import38 from 'ionic-angular/components/menu/menu';
import * as import39 from 'ionic-angular/components/nav/nav';
import * as import40 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import41 from '../../node_modules/ionic-angular/components/menu/menu-close.ngfactory';
import * as import42 from '../../node_modules/ionic-angular/components/avatar/avatar.ngfactory';
import * as import43 from 'ionic-angular/util/form';
import * as import44 from 'ionic-angular/components/item/item-reorder';
import * as import45 from 'ionic-angular/components/avatar/avatar';
import * as import46 from 'ionic-angular/components/item/item';
import * as import47 from 'ionic-angular/components/menu/menu-close';
import * as import48 from '@angular/core/src/security';
import * as import49 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import50 from 'ionic-angular/components/icon/icon';
import * as import51 from '../../node_modules/ionic-angular/components/badge/badge.ngfactory';
import * as import52 from 'ionic-angular/components/badge/badge';
export class Wrapper_MasterPage {
  context:import0.MasterPage;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.MasterPage(p0);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_MasterPage_Host:import2.RenderComponentType = (null as any);
class _View_MasterPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _MasterPage_0_4:Wrapper_MasterPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MasterPage_Host0,renderType_MasterPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MasterPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MasterPage_0_4 = new Wrapper_MasterPage(this.parentInjector.get(import8.ProfileData));
    this._appEl_0.initComponent(this._MasterPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._MasterPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MasterPage) && (0 === requestNodeIndex))) { return this._MasterPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MasterPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MasterPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_MasterPage_Host === (null as any))) { (renderType_MasterPage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_MasterPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const MasterPageNgFactory:import10.ComponentFactory<import0.MasterPage> = new import10.ComponentFactory<import0.MasterPage>('ng-component',viewFactory_MasterPage_Host0,import0.MasterPage);
const styles_MasterPage:any[] = ([] as any[]);
var renderType_MasterPage:import2.RenderComponentType = (null as any);
class _View_MasterPage0 extends import1.AppView<import0.MasterPage> {
  _viewQuery_Nav_0:import11.QueryList<any>;
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Menu_0_4:import12.Wrapper_Menu;
  _query_Content_0_0:import11.QueryList<any>;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Content_2_4:import13.Wrapper_Content;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import14.Wrapper_NgIf;
  _text_5:any;
  _el_6:any;
  _List_6_3:import15.Wrapper_List;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _appEl_8:import3.AppElement;
  _TemplateRef_8_5:any;
  _NgFor_8_6:import16.Wrapper_NgFor;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _Nav_14_4:import17.Wrapper_Nav;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MasterPage0,renderType_MasterPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_Nav_0 = new import11.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-menu',(null as any));
    this.renderer.setElementAttribute(this._el_0,'role','navigation');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import12.viewFactory_Menu0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Menu_0_4 = new import12.Wrapper_Menu(this.parentInjector.get(import18.MenuController),new import19.ElementRef(this._el_0),this.parentInjector.get(import20.Config),this.parentInjector.get(import21.Platform),this.renderer,this.parentInjector.get(import22.Keyboard),this.parentInjector.get(import23.NgZone),this.parentInjector.get(import24.GestureController));
    this._query_Content_0_0 = new import11.QueryList<any>();
    this._appEl_0.initComponent(this._Menu_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n\n\n  ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-content',(null as any));
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import13.viewFactory_Content0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Content_2_4 = new import13.Wrapper_Content(this.parentInjector.get(import20.Config),new import19.ElementRef(this._el_2),this.renderer,this.parentInjector.get(import25.App),this.parentInjector.get(import22.Keyboard),this.parentInjector.get(import23.NgZone),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import27.Tabs,(null as any)));
    this._appEl_2.initComponent(this._Content_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import28.TemplateRef_(this._appEl_4,viewFactory_MasterPage1);
    this._NgIf_4_6 = new import14.Wrapper_NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_6_3 = new import15.Wrapper_List(this.parentInjector.get(import20.Config),new import19.ElementRef(this._el_6),this.renderer,this.parentInjector.get(import24.GestureController));
    this._text_7 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._appEl_8 = new import3.AppElement(8,6,this,this._anchor_8);
    this._TemplateRef_8_5 = new import28.TemplateRef_(this._appEl_8,viewFactory_MasterPage2);
    this._NgFor_8_6 = new import16.Wrapper_NgFor(this._appEl_8.vcRef,this._TemplateRef_8_5,this.parentInjector.get(import29.IterableDiffers),this.ref);
    this._text_9 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Content_2_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._appEl_4,
        this._text_5,
        this._el_6,
        this._text_10
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._query_Content_0_0.reset([this._Content_2_4.context]);
    this._Menu_0_4.context.menuContent = this._query_Content_0_0.first;
      compView_0.create(this._Menu_0_4.context,[([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_11
      ]
    )],(null as any));
    this._text_12 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ion-nav',(null as any));
    this.renderer.setElementAttribute(this._el_14,'swipeBackEnabled','false');
    this._appEl_14 = new import3.AppElement(14,(null as any),this,this._el_14);
    var compView_14:any = import17.viewFactory_Nav0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Nav_14_4 = new import17.Wrapper_Nav(this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import30.NavControllerBase,(null as any)),this.parentInjector.get(import25.App),this.parentInjector.get(import20.Config),this.parentInjector.get(import22.Keyboard),new import19.ElementRef(this._el_14),this.parentInjector.get(import23.NgZone),this.renderer,this.parentInjector.get(import31.ComponentFactoryResolver),this.parentInjector.get(import24.GestureController),this.parentInjector.get(import32.TransitionController),this.parentInjector.get(import33.DeepLinker,(null as any)));
    this._appEl_14.initComponent(this._Nav_14_4.context,([] as any[]),compView_14);
    compView_14.create(this._Nav_14_4.context,([] as any[]),(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._viewQuery_Nav_0.reset([this._Nav_14_4.context]);
    this.context.nav = this._viewQuery_Nav_0.first;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import28.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import34.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    if (((token === import28.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import35.NgFor) && (8 === requestNodeIndex))) { return this._NgFor_8_6.context; }
    if (((token === import36.List) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._List_6_3.context; }
    if (((token === import37.Content) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Content_2_4.context; }
    if (((token === import38.Menu) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Menu_0_4.context; }
    if (((token === import39.Nav) && (14 === requestNodeIndex))) { return this._Nav_14_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this._Nav_14_4.context;
    this._Menu_0_4.check_content(currVal_0,throwOnChange,false);
    if (this._Menu_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    if (this._Content_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    const currVal_2:any = this.context.userProfile;
    this._NgIf_4_6.check_ngIf(currVal_2,throwOnChange,false);
    this._NgIf_4_6.detectChangesInternal(this,this._anchor_4,throwOnChange);
    this._List_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    const currVal_3:any = this.context.pages;
    this._NgFor_8_6.check_ngForOf(currVal_3,throwOnChange,false);
    this._NgFor_8_6.detectChangesInternal(this,this._anchor_8,throwOnChange);
    const currVal_4:any = this.context.rootPage;
    this._Nav_14_4.check_root(currVal_4,throwOnChange,false);
    const currVal_5:any = 'false';
    this._Nav_14_4.check_swipeBackEnabled(currVal_5,throwOnChange,false);
    this._Nav_14_4.detectChangesInternal(this,this._el_14,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this._Content_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_14_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_2_4.context.ngOnDestroy();
    this._Menu_0_4.context.ngOnDestroy();
  }
}
export function viewFactory_MasterPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.MasterPage> {
  if ((renderType_MasterPage === (null as any))) { (renderType_MasterPage = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_MasterPage,{})); }
  return new _View_MasterPage0(viewUtils,parentInjector,declarationEl);
}
class _View_MasterPage1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import40.Wrapper_Item;
  _ItemContent_0_5:import40.Wrapper_ItemContent;
  _MenuClose_0_6:import41.Wrapper_MenuClose;
  _query_Label_0_0:import11.QueryList<any>;
  _query_Button_0_1:import11.QueryList<any>;
  _query_Icon_0_2:import11.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Avatar_2_3:import42.Wrapper_Avatar;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MasterPage1,renderType_MasterPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'menuClose','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import40.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import40.Wrapper_Item(this.parent.parentInjector.get(import43.Form),this.parent.parentInjector.get(import20.Config),new import19.ElementRef(this._el_0),this.renderer,this.parent.parentInjector.get(import44.ItemReorder,(null as any)));
    this._ItemContent_0_5 = new import40.Wrapper_ItemContent();
    this._MenuClose_0_6 = new import41.Wrapper_MenuClose(this.parent.parentInjector.get(import18.MenuController));
    this._query_Label_0_0 = new import11.QueryList<any>();
    this._query_Button_0_1 = new import11.QueryList<any>();
    this._query_Icon_0_2 = new import11.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'item-left','');
    this._Avatar_2_3 = new import42.Wrapper_Avatar();
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'img',(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._text_6,
        this._el_7,
        this._text_9,
        this._el_10,
        this._text_12
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_4,'srcChange',this.eventHandler(this._handle_srcChange_4_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import45.Avatar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Avatar_2_3.context; }
    if (((token === import46.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Item_0_4.context; }
    if (((token === import46.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._ItemContent_0_5.context; }
    if (((token === import47.MenuClose) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._MenuClose_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_2:any = '';
    this._MenuClose_0_6.check_menuClose(currVal_2,throwOnChange,false);
    this._MenuClose_0_6.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Avatar_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_4:any = this.parent.context.userProfile.avatar;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'src',this.viewUtils.sanitizer.sanitize(import48.SecurityContext.URL,currVal_4));
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(2,'',this.parent.context.userProfile.firstName,' ',this.parent.context.userProfile.lastName,'');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_8,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import4.interpolate(1,'',this.parent.context.userProfile.email,'');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_11,currVal_6);
      this._expr_6 = currVal_6;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.goToUserProfile()) !== false);
    const pd_1:any = ((<any>this._MenuClose_0_6.context.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_srcChange_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.userProfile.avatar = $event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_MasterPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_MasterPage1(viewUtils,parentInjector,declarationEl);
}
class _View_MasterPage2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import40.Wrapper_Item;
  _ItemContent_0_5:import40.Wrapper_ItemContent;
  _MenuClose_0_6:import41.Wrapper_MenuClose;
  _query_Label_0_0:import11.QueryList<any>;
  _query_Button_0_1:import11.QueryList<any>;
  _query_Icon_0_2:import11.QueryList<any>;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import14.Wrapper_NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import14.Wrapper_NgIf;
  _text_5:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MasterPage2,renderType_MasterPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this.renderer.setElementAttribute(this._el_0,'menuClose','');
    this.renderer.setElementAttribute(this._el_0,'no-lines','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import40.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import40.Wrapper_Item(this.parent.parentInjector.get(import43.Form),this.parent.parentInjector.get(import20.Config),new import19.ElementRef(this._el_0),this.renderer,this.parent.parentInjector.get(import44.ItemReorder,(null as any)));
    this._ItemContent_0_5 = new import40.Wrapper_ItemContent();
    this._MenuClose_0_6 = new import41.Wrapper_MenuClose(this.parent.parentInjector.get(import18.MenuController));
    this._query_Label_0_0 = new import11.QueryList<any>();
    this._query_Button_0_1 = new import11.QueryList<any>();
    this._query_Icon_0_2 = new import11.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_2 = new import3.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import28.TemplateRef_(this._appEl_2,viewFactory_MasterPage3);
    this._NgIf_2_6 = new import14.Wrapper_NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_4 = new import3.AppElement(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import28.TemplateRef_(this._appEl_4,viewFactory_MasterPage4);
    this._NgIf_4_6 = new import14.Wrapper_NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]).concat([this._appEl_2]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._text_3,
        this._text_5
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._appEl_4])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import28.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import34.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    if (((token === import28.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import34.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    if (((token === import46.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Item_0_4.context; }
    if (((token === import46.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ItemContent_0_5.context; }
    if (((token === import47.MenuClose) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._MenuClose_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_2:any = '';
    this._MenuClose_0_6.check_menuClose(currVal_2,throwOnChange,false);
    this._MenuClose_0_6.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_3:any = this.context.$implicit.icon;
    this._NgIf_2_6.check_ngIf(currVal_3,throwOnChange,false);
    this._NgIf_2_6.detectChangesInternal(this,this._anchor_2,throwOnChange);
    const currVal_5:any = this.context.$implicit.badge;
    this._NgIf_4_6.check_ngIf(currVal_5,throwOnChange,false);
    this._NgIf_4_6.detectChangesInternal(this,this._anchor_4,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
          this._query_Icon_0_2.reset([this._appEl_2.mapNestedViews(_View_MasterPage3,(nestedView:_View_MasterPage3):any => {
            return [nestedView._Icon_0_3.context];
        })]);
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_4:any = import4.interpolate(1,'\n        ',this.context.$implicit.title,'\n        ');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_3,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openPage(this.context.$implicit)) !== false);
    const pd_1:any = ((<any>this._MenuClose_0_6.context.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_MasterPage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_MasterPage2(viewUtils,parentInjector,declarationEl);
}
class _View_MasterPage3 extends import1.AppView<any> {
  _el_0:any;
  _Icon_0_3:import49.Wrapper_Icon;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MasterPage3,renderType_MasterPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_0,'item-left','');
    this.renderer.setElementAttribute(this._el_0,'role','img');
    this._Icon_0_3 = new import49.Wrapper_Icon(this.parent.parent.parentInjector.get(import20.Config),new import19.ElementRef(this._el_0),this.renderer);
    this._expr_1 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import50.Icon) && (0 === requestNodeIndex))) { return this._Icon_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.$implicit.icon,'');
    this._Icon_0_3.check_name(currVal_0,throwOnChange,false);
    this._Icon_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this._Icon_0_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_0,'hide',currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_MasterPage2>this.parent)._query_Icon_0_2.setDirty();
  }
  destroyInternal():void {
    this._Icon_0_3.context.ngOnDestroy();
  }
}
function viewFactory_MasterPage3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_MasterPage3(viewUtils,parentInjector,declarationEl);
}
class _View_MasterPage4 extends import1.AppView<any> {
  _el_0:any;
  _Badge_0_3:import51.Wrapper_Badge;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MasterPage4,renderType_MasterPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-badge',(null as any));
    this.renderer.setElementAttribute(this._el_0,'item-right','');
    this._Badge_0_3 = new import51.Wrapper_Badge(this.parent.parent.parentInjector.get(import20.Config),new import19.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import52.Badge) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Badge_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Badge_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.$implicit.badge,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MasterPage4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_MasterPage4(viewUtils,parentInjector,declarationEl);
}