/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './dish-list';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../providers/dish-data';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import22 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/fab/fab.ngfactory';
import * as import24 from 'ionic-angular/config/config';
import * as import25 from '@angular/core/src/linker/element_ref';
import * as import26 from 'ionic-angular/navigation/view-controller';
import * as import27 from 'ionic-angular/components/app/app';
import * as import28 from 'ionic-angular/components/menu/menu-controller';
import * as import29 from 'ionic-angular/components/toolbar/toolbar';
import * as import30 from 'ionic-angular/util/keyboard';
import * as import31 from '@angular/core/src/zone/ng_zone';
import * as import32 from 'ionic-angular/components/tabs/tabs';
import * as import33 from 'ionic-angular/gestures/gesture-controller';
import * as import34 from '@angular/core/src/linker/template_ref';
import * as import35 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import36 from 'ionic-angular/components/icon/icon';
import * as import37 from 'ionic-angular/components/button/button';
import * as import38 from 'ionic-angular/components/menu/menu-toggle';
import * as import39 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import40 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import41 from 'ionic-angular/components/navbar/navbar';
import * as import42 from '@angular/common/src/directives/ng_for';
import * as import43 from 'ionic-angular/components/list/list';
import * as import44 from 'ionic-angular/components/fab/fab';
import * as import45 from 'ionic-angular/components/content/content';
import * as import46 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import47 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import48 from '../../node_modules/ionic-angular/components/thumbnail/thumbnail.ngfactory';
import * as import49 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import50 from 'ionic-angular/util/form';
import * as import51 from 'ionic-angular/components/item/item-reorder';
import * as import52 from 'ionic-angular/components/thumbnail/thumbnail';
import * as import53 from 'ionic-angular/components/item/item';
import * as import54 from 'ionic-angular/components/grid/grid';
import * as import55 from 'ionic-angular/components/card/card';
import * as import56 from '@angular/core/src/security';
export class Wrapper_DishListPage {
  context:import0.DishListPage;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.DishListPage(p0,p1);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_DishListPage_Host:import2.RenderComponentType = (null as any);
class _View_DishListPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _DishListPage_0_4:Wrapper_DishListPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_DishListPage_Host0,renderType_DishListPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-dish-list',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_DishListPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DishListPage_0_4 = new Wrapper_DishListPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.DishData));
    this._appEl_0.initComponent(this._DishListPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._DishListPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.DishListPage) && (0 === requestNodeIndex))) { return this._DishListPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DishListPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DishListPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_DishListPage_Host === (null as any))) { (renderType_DishListPage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_DishListPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const DishListPageNgFactory:import11.ComponentFactory<import0.DishListPage> = new import11.ComponentFactory<import0.DishListPage>('page-dish-list',viewFactory_DishListPage_Host0,import0.DishListPage);
const styles_DishListPage:any[] = ([] as any[]);
var renderType_DishListPage:import2.RenderComponentType = (null as any);
class _View_DishListPage0 extends import1.AppView<import0.DishListPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import12.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import13.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _Button_5_4:import14.Wrapper_Button;
  _MenuToggle_5_5:import15.Wrapper_MenuToggle;
  _ToolbarItem_5_6:import16.Wrapper_ToolbarItem;
  _query_Button_5_0:import17.QueryList<any>;
  _text_6:any;
  _el_7:any;
  _Icon_7_3:import18.Wrapper_Icon;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _ToolbarItem_10_3:import16.Wrapper_ToolbarItem;
  _query_Button_10_0:import17.QueryList<any>;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _ToolbarTitle_14_4:import19.Wrapper_ToolbarTitle;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  /*private*/ _appEl_19:import3.AppElement;
  _Content_19_4:import20.Wrapper_Content;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _List_22_3:import21.Wrapper_List;
  _text_23:any;
  _anchor_24:any;
  /*private*/ _appEl_24:import3.AppElement;
  _TemplateRef_24_5:any;
  _NgFor_24_6:import22.Wrapper_NgFor;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  /*private*/ _appEl_27:import3.AppElement;
  _FabContainer_27_4:import23.Wrapper_FabContainer;
  _query_FabButton_27_0:import17.QueryList<any>;
  _query_FabList_27_1:import17.QueryList<any>;
  _text_28:any;
  _el_29:any;
  /*private*/ _appEl_29:import3.AppElement;
  _FabButton_29_4:import23.Wrapper_FabButton;
  _text_30:any;
  _el_31:any;
  _Icon_31_3:import18.Wrapper_Icon;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_14:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_DishListPage0,renderType_DishListPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import12.Wrapper_Header(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import26.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this.renderer.setElementAttribute(this._el_3,'color','primary');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import13.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import13.Wrapper_Navbar(this.parentInjector.get(import27.App),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_5,'ion-button','');
    this.renderer.setElementAttribute(this._el_5,'menuToggle','');
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import14.viewFactory_Button0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Button_5_4 = new import14.Wrapper_Button('','',this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_5),this.renderer);
    this._MenuToggle_5_5 = new import15.Wrapper_MenuToggle(this.parentInjector.get(import28.MenuController),new import25.ElementRef(this._el_5),this.parentInjector.get(import26.ViewController,(null as any)),this._Navbar_3_4.context);
    this._ToolbarItem_5_6 = new import16.Wrapper_ToolbarItem(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import29.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._query_Button_5_0 = new import17.QueryList<any>();
    this._appEl_5.initComponent(this._Button_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_7,'name','menu');
    this.renderer.setElementAttribute(this._el_7,'role','img');
    this._Icon_7_3 = new import18.Wrapper_Icon(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_7),this.renderer);
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_5.create(this._Button_5_4.context,[([] as any[]).concat([
        this._text_6,
        this._el_7,
        this._text_8
      ]
    )],(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_10,'start','');
    this._ToolbarItem_10_3 = new import16.Wrapper_ToolbarItem(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import29.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._query_Button_10_0 = new import17.QueryList<any>();
    this._text_11 = this.renderer.createText(this._el_10,'\n      ',(null as any));
    this._text_12 = this.renderer.createText(this._el_10,'\n    ',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_14 = new import3.AppElement(14,3,this,this._el_14);
    var compView_14:any = import19.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(14),this._appEl_14);
    this._ToolbarTitle_14_4 = new import19.Wrapper_ToolbarTitle(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import29.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_14.initComponent(this._ToolbarTitle_14_4.context,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'',(null as any));
    compView_14.create(this._ToolbarTitle_14_4.context,[([] as any[]).concat([this._text_15])],(null as any));
    this._text_16 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]).concat([this._el_5]),
      ([] as any[]).concat([this._el_10]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_4,
        this._text_9,
        this._text_13,
        this._el_14,
        this._text_16
      ]
      )
    ]
    ,(null as any));
    this._text_17 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_18 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_19 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_19,'padding','');
    this._appEl_19 = new import3.AppElement(19,(null as any),this,this._el_19);
    var compView_19:any = import20.viewFactory_Content0(this.viewUtils,this.injector(19),this._appEl_19);
    this._Content_19_4 = new import20.Wrapper_Content(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_19),this.renderer,this.parentInjector.get(import27.App),this.parentInjector.get(import30.Keyboard),this.parentInjector.get(import31.NgZone),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import32.Tabs,(null as any)));
    this._appEl_19.initComponent(this._Content_19_4.context,([] as any[]),compView_19);
    this._text_20 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_22_3 = new import21.Wrapper_List(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_22),this.renderer,this.parentInjector.get(import33.GestureController));
    this._text_23 = this.renderer.createText(this._el_22,'\n    ',(null as any));
    this._anchor_24 = this.renderer.createTemplateAnchor(this._el_22,(null as any));
    this._appEl_24 = new import3.AppElement(24,22,this,this._anchor_24);
    this._TemplateRef_24_5 = new import34.TemplateRef_(this._appEl_24,viewFactory_DishListPage1);
    this._NgFor_24_6 = new import22.Wrapper_NgFor(this._appEl_24.vcRef,this._TemplateRef_24_5,this.parentInjector.get(import35.IterableDiffers),this.ref);
    this._text_25 = this.renderer.createText(this._el_22,'\n  ',(null as any));
    this._text_26 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_27 = this.renderer.createElement((null as any),'ion-fab',(null as any));
    this.renderer.setElementAttribute(this._el_27,'bottom','');
    this.renderer.setElementAttribute(this._el_27,'right','');
    this._appEl_27 = new import3.AppElement(27,19,this,this._el_27);
    var compView_27:any = import23.viewFactory_FabContainer0(this.viewUtils,this.injector(27),this._appEl_27);
    this._FabContainer_27_4 = new import23.Wrapper_FabContainer(new import25.ElementRef(this._el_27));
    this._query_FabButton_27_0 = new import17.QueryList<any>();
    this._query_FabList_27_1 = new import17.QueryList<any>();
    this._appEl_27.initComponent(this._FabContainer_27_4.context,([] as any[]),compView_27);
    this._text_28 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_29 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_29,'color','primary');
    this.renderer.setElementAttribute(this._el_29,'ion-fab','');
    this._appEl_29 = new import3.AppElement(29,27,this,this._el_29);
    var compView_29:any = import23.viewFactory_FabButton0(this.viewUtils,this.injector(29),this._appEl_29);
    this._FabButton_29_4 = new import23.Wrapper_FabButton(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_29),this.renderer);
    this._appEl_29.initComponent(this._FabButton_29_4.context,([] as any[]),compView_29);
    this._text_30 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_31 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_31,'name','add');
    this.renderer.setElementAttribute(this._el_31,'role','img');
    this._Icon_31_3 = new import18.Wrapper_Icon(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_31),this.renderer);
      compView_29.create(this._FabButton_29_4.context,[([] as any[]).concat([
        this._text_30,
        this._el_31
      ]
    )],(null as any));
    this._text_32 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_FabButton_27_0.reset([this._FabButton_29_4.context]);
    this._FabContainer_27_4.context._mainButton = this._query_FabButton_27_0.first;
      compView_27.create(this._FabContainer_27_4.context,[([] as any[]).concat([
        this._text_28,
        this._el_29,
        this._text_32
      ]
    )],(null as any));
    this._text_33 = this.renderer.createText((null as any),'\n',(null as any));
    compView_19.create(this._Content_19_4.context,[
      ([] as any[]).concat([this._el_27]),
      ([] as any[]).concat([
        this._text_20,
        this._text_21,
        this._el_22,
        this._text_26,
        this._text_33
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_34 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_29,'click',this.eventHandler(this._handle_click_29_0.bind(this)));
    this._expr_14 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._anchor_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import36.Icon) && (7 === requestNodeIndex))) { return this._Icon_7_3.context; }
    if (((token === import37.Button) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Button_5_4.context; }
    if (((token === import38.MenuToggle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._MenuToggle_5_5.context; }
    if (((token === import39.ToolbarItem) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ToolbarItem_5_6.context; }
    if (((token === import39.ToolbarItem) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._ToolbarItem_10_3.context; }
    if (((token === import40.ToolbarTitle) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._ToolbarTitle_14_4.context; }
    if (((token === import41.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Navbar_3_4.context; }
    if (((token === import29.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Header_1_3.context; }
    if (((token === import34.TemplateRef) && (24 === requestNodeIndex))) { return this._TemplateRef_24_5; }
    if (((token === import42.NgFor) && (24 === requestNodeIndex))) { return this._NgFor_24_6.context; }
    if (((token === import43.List) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._List_22_3.context; }
    if (((token === import36.Icon) && (31 === requestNodeIndex))) { return this._Icon_31_3.context; }
    if (((token === import44.FabButton) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._FabButton_29_4.context; }
    if (((token === import44.FabContainer) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._FabContainer_27_4.context; }
    if (((token === import45.Content) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Content_19_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    const currVal_0:any = 'primary';
    this._Navbar_3_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._Button_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    const currVal_4:any = '';
    this._MenuToggle_5_5.check_menuToggle(currVal_4,throwOnChange,false);
    this._MenuToggle_5_5.detectChangesInternal(this,this._el_5,throwOnChange);
    this._ToolbarItem_5_6.detectChangesInternal(this,this._el_5,throwOnChange);
    const currVal_6:any = 'menu';
    this._Icon_7_3.check_name(currVal_6,throwOnChange,false);
    this._Icon_7_3.detectChangesInternal(this,this._el_7,throwOnChange);
    this._ToolbarItem_10_3.detectChangesInternal(this,this._el_10,throwOnChange);
    if (this._ToolbarTitle_14_4.detectChangesInternal(this,this._el_14,throwOnChange)) { this._appEl_14.componentView.markAsCheckOnce(); }
    if (this._Content_19_4.detectChangesInternal(this,this._el_19,throwOnChange)) { this._appEl_19.componentView.markAsCheckOnce(); }
    this._List_22_3.detectChangesInternal(this,this._el_22,throwOnChange);
    const currVal_10:any = this.context.dishList;
    this._NgFor_24_6.check_ngForOf(currVal_10,throwOnChange,false);
    this._NgFor_24_6.detectChangesInternal(this,this._anchor_24,throwOnChange);
    this._FabContainer_27_4.detectChangesInternal(this,this._el_27,throwOnChange);
    const currVal_12:any = 'primary';
    this._FabButton_29_4.check_color(currVal_12,throwOnChange,false);
    if (this._FabButton_29_4.detectChangesInternal(this,this._el_29,throwOnChange)) { this._appEl_29.componentView.markAsCheckOnce(); }
    const currVal_13:any = 'add';
    this._Icon_31_3.check_name(currVal_13,throwOnChange,false);
    this._Icon_31_3.detectChangesInternal(this,this._el_31,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_5_0.dirty) {
        this._query_Button_5_0.reset([this._Button_5_4.context]);
        this._ToolbarItem_5_6.context._buttons = this._query_Button_5_0;
        this._query_Button_5_0.notifyOnChanges();
      }
      if (this._query_Button_10_0.dirty) {
        this._query_Button_10_0.reset(([] as any[]));
        this._ToolbarItem_10_3.context._buttons = this._query_Button_10_0;
        this._query_Button_10_0.notifyOnChanges();
      }
      if (this._query_FabList_27_1.dirty) {
        this._query_FabList_27_1.reset(([] as any[]));
        this._FabContainer_27_4.context._fabLists = this._query_FabList_27_1;
        this._query_FabList_27_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_5_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._FabContainer_27_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._MenuToggle_5_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_5,'hidden',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_7:any = this._Icon_7_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_7,'hide',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = import4.interpolate(1,'Près de ',this.context.addressDisplayText,'');
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_15,currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._Content_19_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_19,'statusbar-padding',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_14:any = this._Icon_31_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_31,'hide',currVal_14);
      this._expr_14 = currVal_14;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_7_3.context.ngOnDestroy();
    this._Icon_31_3.context.ngOnDestroy();
    this._FabContainer_27_4.context.ngOnDestroy();
    this._Content_19_4.context.ngOnDestroy();
  }
  private _handle_click_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_5_5.context.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_click_29_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.goToDishCreate()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_DishListPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.DishListPage> {
  if ((renderType_DishListPage === (null as any))) { (renderType_DishListPage = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_DishListPage,{})); }
  return new _View_DishListPage0(viewUtils,parentInjector,declarationEl);
}
class _View_DishListPage1 extends import1.AppView<any> {
  _el_0:any;
  _Card_0_3:import46.Wrapper_Card;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Item_2_4:import47.Wrapper_Item;
  _ItemContent_2_5:import47.Wrapper_ItemContent;
  _query_Label_2_0:import17.QueryList<any>;
  _query_Button_2_1:import17.QueryList<any>;
  _query_Icon_2_2:import17.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _Thumbnail_4_3:import48.Wrapper_Thumbnail;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _Row_16_3:import49.Wrapper_Row;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _Col_19_3:import49.Wrapper_Col;
  _text_20:any;
  _el_21:any;
  _Icon_21_3:import18.Wrapper_Icon;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _Col_24_3:import49.Wrapper_Col;
  _text_25:any;
  _el_26:any;
  _Icon_26_3:import18.Wrapper_Icon;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_DishListPage1,renderType_DishListPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_0_3 = new import46.Wrapper_Card(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this.renderer.setElementAttribute(this._el_2,'no-lines','');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import47.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import47.Wrapper_Item(this.parent.parentInjector.get(import50.Form),this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_2),this.renderer,this.parent.parentInjector.get(import51.ItemReorder,(null as any)));
    this._ItemContent_2_5 = new import47.Wrapper_ItemContent();
    this._query_Label_2_0 = new import17.QueryList<any>();
    this._query_Button_2_1 = new import17.QueryList<any>();
    this._query_Icon_2_2 = new import17.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-thumbnail',(null as any));
    this.renderer.setElementAttribute(this._el_4,'item-left','');
    this._Thumbnail_4_3 = new import48.Wrapper_Thumbnail();
    this._text_5 = this.renderer.createText(this._el_4,'\n          ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'img',(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_2_0.reset(([] as any[]));
    this._Item_2_4.context.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4.context,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11,
        this._el_12,
        this._text_14
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_0,'ion-row',(null as any));
    this._Row_16_3 = new import49.Wrapper_Row();
    this._text_17 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._text_18 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_16,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_19,'center','');
    this.renderer.setElementAttribute(this._el_19,'text-center','');
    this._Col_19_3 = new import49.Wrapper_Col();
    this._text_20 = this.renderer.createText(this._el_19,'\n          ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_21,'name','restaurant');
    this.renderer.setElementAttribute(this._el_21,'role','img');
    this._Icon_21_3 = new import18.Wrapper_Icon(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_21),this.renderer);
    this._text_22 = this.renderer.createText(this._el_19,'',(null as any));
    this._text_23 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_16,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_24,'center','');
    this.renderer.setElementAttribute(this._el_24,'text-center','');
    this._Col_24_3 = new import49.Wrapper_Col();
    this._text_25 = this.renderer.createText(this._el_24,'\n          ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_26,'name','pricetag');
    this.renderer.setElementAttribute(this._el_26,'role','img');
    this._Icon_26_3 = new import18.Wrapper_Icon(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_26),this.renderer);
    this._text_27 = this.renderer.createText(this._el_24,'',(null as any));
    this._text_28 = this.renderer.createText(this._el_16,'\n      ',(null as any));
    this._text_29 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_6,'srcChange',this.eventHandler(this._handle_srcChange_6_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import52.Thumbnail) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Thumbnail_4_3.context; }
    if (((token === import53.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Item_2_4.context; }
    if (((token === import53.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._ItemContent_2_5.context; }
    if (((token === import36.Icon) && (21 === requestNodeIndex))) { return this._Icon_21_3.context; }
    if (((token === import54.Col) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Col_19_3.context; }
    if (((token === import36.Icon) && (26 === requestNodeIndex))) { return this._Icon_26_3.context; }
    if (((token === import54.Col) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Col_24_3.context; }
    if (((token === import54.Row) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Row_16_3.context; }
    if (((token === import55.Card) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Card_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Card_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    if (this._Item_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    this._ItemContent_2_5.detectChangesInternal(this,this._el_2,throwOnChange);
    this._Thumbnail_4_3.detectChangesInternal(this,this._el_4,throwOnChange);
    this._Row_16_3.detectChangesInternal(this,this._el_16,throwOnChange);
    this._Col_19_3.detectChangesInternal(this,this._el_19,throwOnChange);
    const currVal_5:any = 'restaurant';
    this._Icon_21_3.check_name(currVal_5,throwOnChange,false);
    this._Icon_21_3.detectChangesInternal(this,this._el_21,throwOnChange);
    this._Col_24_3.detectChangesInternal(this,this._el_24,throwOnChange);
    const currVal_8:any = 'pricetag';
    this._Icon_26_3.check_name(currVal_8,throwOnChange,false);
    this._Icon_26_3.detectChangesInternal(this,this._el_26,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset(([] as any[]));
        this._Item_2_4.context._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset(([] as any[]));
        this._Item_2_4.context._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.context.ngAfterContentInit(); }
    }
    const currVal_2:any = this.context.$implicit.photo;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_6,'src',this.viewUtils.sanitizer.sanitize(import56.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_10,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(1,'\n          ',this.context.$implicit.description,'\n        ');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_13,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_21_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_21,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = import4.interpolate(1,'\n          ',this.context.$implicit.portionsLeftNumber,'\n        ');
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_22,currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_9:any = this._Icon_26_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_26,'hide',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = import4.interpolate(1,'\n          ',this.context.$implicit.price,'€\n        ');
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setText(this._text_27,currVal_10);
      this._expr_10 = currVal_10;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_21_3.context.ngOnDestroy();
    this._Icon_26_3.context.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.goToDishDetail(this.context.$implicit.id)) !== false);
    return (true && pd_0);
  }
  private _handle_srcChange_6_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.$implicit.photo = $event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_DishListPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_DishListPage1(viewUtils,parentInjector,declarationEl);
}